### ISSUE TITLE
Incorrect Password :(

### ISSUE THREAD

**Issue by rogerlawrence79** [dustindclark/homebridge-envisalink#1]
I'm not sure if this is the correct place for this type challenge / question...

I get:

```
server bound
actual connected
Login Request Response: 3
login requested... sending response...
sendcommand 005<**mypassword**>6c
Command 005 Acknowledged
Login Request Response: 0
Incorrect Password :(
actual disconnected
```
- I've tried 
   my panel password,
   the password used for the local alarm web interface.
   my eyezon password.

Snip from my JSON:
`
            "platform": "Envisalink",
            "host": "10.10.11.134",
            "deviceType": "DSC",
            "password": "<my user password to the local web interface>",
            "pin": "<my panel password>",
            "suppressZoneAccessories": false,
`

EnvisaLink Firmware:  01.12.174

**Comment by rogerlawrence79** [comment]
- I found that it needs to be a 6 digit password not 4.  So I've updated the password to 6 digits.
- After that I was able to telnet in to port 4025 using the login command "005passwordca"
- It appears that the the envisalink plugin for homebridge is using "005passwordd6"  Which is still giving me a 5050Ca (Wrong Password) ... Though I'm not sure exactly what the CA or D6 standfor or mean.

**Comment by rogerlawrence79** [comment]
Found that the checksum needs to be upper case... So in the index.js file for nodealarmproxy... I changed:
- checksum = checksum.toString(16).slice(-2);

to 
- checksum = checksum.toString(16).slice(-2).toUpperCase();

Now its appears to be logging in correctly.

**Comment by rogerlawrence79** [comment]
Note that its already fixed on Github already :) ... Its only on NPM where its broken...

**Comment by dustindclark** [comment]
Hi Roger,

Sorry for the delay.  Now that you mention it, that sounds very familiar.
I may have even contributed the fix to that repo.  I'll try to reach out to
the repo owner to see if he/she can publish.  Thanks.

Dustin

Sent from my iPhone

On Jun 27, 2016, at 6:44 PM, rogerlawrence79 notifications@github.com
wrote:

Note that its already fixed on Github already :) ... Its only on NPM where
its broken...

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/dustindclark/homebridge-envisalink/issues/1#issuecomment-228908978,
or mute the thread
https://github.com/notifications/unsubscribe/ADpJoDATURrI53Iuc111zAL3N0p0ibGLks5qQGBVgaJpZM4I-pud
.

**Comment by zbuttram** [comment]
Hey @dustindclark, I was looking into this with @rogerlawrence79 (we work together). Looks like the issue was in fact fixed, and the fix is present in the NodeAlarmProxy repo, but the fix isn't pushed to NPM or the package.json on this repo is using an older version? Not sure on that last part.

**Comment by IMNotMax** [comment]
Hi,
I've just installed homebridge-envisalink on my raspberry pi, and I have the issue.
The repo of NodeAlarmProxy is not up to date...
I had to manually find the NodeAlarmProxy index.js and add .ToUpperCase

For those who are not familiar, here the folder ton find the index.js
cd /usr/local/lib/node_modules/homebridge-envisalink/node_modules/nodealarmproxy/
and to edit the file: sudo nano index.js

**Comment by dustindclark** [comment]
This issue is pending the publish of the latest NodeAlarmProxy package.

**Comment by lsmith07** [comment]
When I installed homebridge-envisalink 3 days ago (11/19/16), the index.js file for NodeAlarmProxy reflected the updated code:  checksum = checksum.toString(16).slice(-2).toUpperCase();

Without changing any coding in the NodeAlarmProxy module after it was installed with this plugin, everything works perfectly (once I worked through issue #7).
