### ISSUE TITLE
Motorized Doors and Windows

### ISSUE THREAD

**Issue by dhcantwell** [dustindclark/homebridge-envisalink#10]
I have the plugin working fine so far with no real issues.  Only thing I have noticed is the HomeKit thinks that the Window and Door sensors on the alarm system are "motorized" windows and doors.  Is there a way to make HomeKit see these as just open/closed manual windows and doors?  When you tap the accessory icon in the Home app it tries to open the door, and when you manually open the door it shows as "opening" rather than "opened".

**Comment by erfind** [comment]
I had changed mine to be recognized as motion sensors. This seems to work as triggered when open and then not triggered when closed.

**Comment by blysik** [comment]
Should they instead be changed to 'Contact Sensors' ?

**Comment by blysik** [comment]
... of course the plugin would need to be modified to have the idea of contact sensors.  ie, open/close sensors.

**Comment by lfiocco** [comment]
I have the first generation ip100. Does this work?  Are you able to get zone changes in realtime from the home app?  Can I get the evl-4 to work with this app? Can you use the sensors to setup triggers?

**Comment by ToddGreenfield** [comment]
@lfiocco yes, zone changes are reflected in (near) real-time, maybe 1-3 second delays. I have noticed that without a home hub (iPad or ATV) that the delay is more significant though. @dhcantwell @erfind are you still seeing the sensors show up as motorized? I am not seeing this.

**Comment by dustindclark** [comment]
Closing out old issue.  Doors/windows do not show up as motorized in latest version of this plugin/HomeBridge/HomeKit.

**Comment by dustindclark** [comment]
Please re-open if this persists.
