### ISSUE TITLE
Night Mode isn't reflected in HomeKit when set physically from keypad

### ISSUE THREAD

**Issue by n8847** [dustindclark/homebridge-envisalink#101]
Hi, 
Just upgraded to 1.1.1. 
now when arming for stay on the panel it sets as away in home app. When pressing *9 (setting no entry delay) from panel it sets home to night. I like the last part as this was how I managed my alarm before home bridge when using it with envisalink to vera ui. Best would be if plug-in could set to distinguish between if I press *9 or not and setting it to home unless *9 is pressed when it sets to night. WIth Vera I could set to away, Home, night and off and all would trigger unique scenarios.

**Comment by dustindclark** [comment]
To make sure that I'm understanding, all is working from the homebridge perspective, except when you manually set the alarm to night mode using the keypad? And in this case, you want the correct mode to appear in HomeKit?

**Comment by dustindclark** [comment]
Unable to recreate in 1.2.7. Please re-open if you are still seeing this issue.
