### ISSUE TITLE
Plugin hangs following dropped connection

### ISSUE THREAD

**Issue by jmjlai** [dustindclark/homebridge-envisalink#102]
I received the following after a HomeKit automation attempted to "Night" arm the system.
Following this, the homebridge-envisalink plugin became unresponsive in HomeKit until the child bridge was restarted. 
I'm running homebridge-envisalink v1.1.1 on Node.js v16.13.2

```
 [homebridge-envisalink] Failed to connect to Envisalink Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:220:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
```

**Comment by dustindclark** [comment]
Closing in favor of #93.
