### ISSUE TITLE
Envisalink connection issue

### ISSUE THREAD

**Issue by walschots** [dustindclark/homebridge-envisalink#105]
Not sure what changed - this week I started to see this error on my HB:

[Envisalink] Failed to connect to Envisalink Error: connect ECONNRESET 192.168.7.187:4025
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'connect',
  address: '192.168.7.187',
  port: 4025
}

Any recommendations?

**Comment by dustindclark** [comment]
Closing in favor of #93.
