### ISSUE TITLE
Ready State Notification

### ISSUE THREAD

**Issue by donmoss1** [dustindclark/homebridge-envisalink#106]
Right now the alarm tells me “Off” when it is disarmed. I would like to see a “Ready” state on my devices if the  partition is able to be armed. Words or color changes would be a great addition as I have to check to alarm keypad to know I can arm a partition. Thanks for your consideration.

**Comment by dustindclark** [comment]
Unfortunately, HomeKit doesn't support this kind of feature. Please re-open if you're aware of other devices that behave in this way.

**Comment by donmoss1** [comment]
Dustin,

I am now confused. I have two switches in my Home App that is listed under my alarm and I am not sure what they do. Is one of them a zone bypass switch? What is the other? They only show in the Home  App and I don’t see them in Homebridge. Please help me understand.


Don

**Comment by readylmay** [comment]
Chime On / Off. You can also go in and edit the details of the accessory to name them appropriately.

From: donmoss1 ***@***.***>
Reply-To: dustindclark/homebridge-envisalink ***@***.***>
Date: Sunday, November 6, 2022 at 4:31 PM
To: dustindclark/homebridge-envisalink ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [dustindclark/homebridge-envisalink] Ready State Notification (Issue #106)

Dustin,

I am now confused. I have two switches in my Home App that is listed under my alarm and I am not sure what they do. Is one of them a zone bypass switch? What is the other? They only show in the Home App and I don’t see them in Homebridge. Please help me understand.


Don

**Comment by donmoss1** [comment]
OK what does the other do? I just installed the update and I can’t find any docs?

Don

**Comment by readylmay** [comment]
Yup, zone bypass.

If you set alarm via homekit, if turned on, it will go through all open zones and bypass them before arming.

From: donmoss1 ***@***.***>
Reply-To: dustindclark/homebridge-envisalink ***@***.***>
Date: Sunday, November 6, 2022 at 4:36 PM
To: dustindclark/homebridge-envisalink ***@***.***>
Cc: Laurent May ***@***.***>, Comment ***@***.***>
Subject: Re: [dustindclark/homebridge-envisalink] Ready State Notification (Issue #106)

OK what does the other do? I just installed the update and I can’t find any docs?

Don

**Comment by donmoss1** [comment]
Will it check all 3 of my partitions or just the main one?

Don

**Comment by dustindclark** [comment]
One is Chime on/off, one is a bypass switch. The duplicate label issue is an iOS bug. More info in the release notes here: https://github.com/dustindclark/homebridge-envisalink/releases/tag/v1.2.0

**Comment by donmoss1** [comment]
Dustin,

I have 3 partitions in my alarm and I am only seeing one new switch in Home App and none in Homebridge. I will do some testing tomorrow and see what I can find. The doc you sent seems to indicate there would be a switch for each partition. Thanks for your help.

Don

**Comment by donmoss1** [comment]
Dustin,

I have 3 partitions in my alarm and I am only seeing one new switch in Home App and none in Homebridge. I will do some testing tomorrow and see what I can find. The doc you sent seems to indicate there would be a switch for each partition. Thanks for your help.

Don
