### ISSUE TITLE
Error connecting to Envisalink

### ISSUE THREAD

**Issue by tron786** [dustindclark/homebridge-envisalink#109]
Was working well. Now does not connect. Rebooted the EVL4 and still nothing 

Log of error below

ERROR. Failed to connect to Envisalink Error: connect ECONNRESET 192.168.0.120:4025
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) {
  errno: -104,

Please advise @dustindclark

**Comment by dustindclark** [comment]
Either something is already connected to the envisalink on that port or the envisalink IP address changed.

Dustin

**Comment by tron786** [comment]
IP address is correct but I do have home assistant also connecting to the EVL4. Could this be an issue? 
How do I solve this ?

**Comment by dustindclark** [comment]
Yes, the envisalink only supports one connection. You should be able to enable the proxy in plugin config, and then configure the other connection connect to the Homebridge IP/proxy port...but I have not tested this.

Dustin

**Comment by dustindclark** [comment]
Closing in favor of #93.
