### ISSUE TITLE
duplicate/conflicting notifications

### ISSUE THREAD

**Issue by scaryfast8750** [dustindclark/homebridge-envisalink#111]
Homebridge 1.5 
Envisalink for DSC plugin 1.1.1

This has been happening for a while but I was troubleshooting and can't seem to figure out why.  

Scenarios:
1.  when My home account sets the alarm to "stay", I get a Stay alarm set notification from HomeKit.  my wife's phone with her own Home use gets two notifications "Away" then followed by "Stay".
2. When her account sets the alarm, its inverted...she gets a single notification.  I get two notifications Away then Stay.

I am not sure exactly when this started but its been happening for a few months at least...but not always.   I see no errors in the debug logs and only see the "stay" state set In home bridge.

**Comment by dustindclark** [comment]
Duplicates #100
