### ISSUE TITLE
Question about Smoke Detectors

### ISSUE THREAD

**Issue by scaryfast8750** [dustindclark/homebridge-envisalink#112]
@dustindclark Not an issue, a question.  How do you add smoke detectors into the config...Do they have their own zone number?  and are the identified separately or all of them as a single "smoke detector"?

Here is my config...it works great other than no smoke detectors in HomeKit.  

{
            "host": "envisalink.localdomain",
            "password": "*******",
            "pin": "****",
            "port": 4025,
            "proxyPort": 4026,
            "enableVerboseLogging": false,
            "suppressZoneAccessories": false,
            "suppressClockReset": false,
            "policePanic": {
                "enabled": false,
                "name": "Police Panic"
            },
            "ambulancePanic": {
                "enabled": false,
                "name": "Ambulance Panic"
            },
            "firePanic": {
                "enabled": false,
                "name": "Fire Panic"
            },
            "partitions": [
                {
                    "name": "Alarm",
                    "enableChimeSwitch": false
                }
            ],
            "zones": [
                {
                    "name": "Front Door",
                    "partition": 1,
                    "zoneNumber": 1,
                    "type": "door"
                },
                {
                    "name": "Motion Detection",
                    "partition": 1,
                    "zoneNumber": 2,
                    "type": "motion"
                },
                {
                    "name": "Kitchen Door",
                    "partition": 1,
                    "zoneNumber": 3,
                    "type": "door"
                },
                {
                    "name": "Patio Door",
                    "partition": 1,
                    "zoneNumber": 4,
                    "type": "door"
                },
                {
                    "name": "Guest Room",
                    "partition": 1,
                    "zoneNumber": 5,
                    "type": "door"
                },
                {
                    "name": "Kitchen Window",
                    "partition": 1,
                    "zoneNumber": 6,
                    "type": "window"
                },
                {
                    "name": "Living Room WIndows",
                    "partition": 1,
                    "zoneNumber": 7,
                    "type": "window"
                },
                {
                    "name": "Master Bedroom Windows",
                    "partition": 1,
                    "zoneNumber": 8,
                    "type": "window"
                },
                {
                    "name": "Guest Bedroom Windows",
                    "partition": 1,
                    "zoneNumber": 9,
                    "type": "window"
                },
                {
                    "name": "Guest Bedroom Windows",
                    "partition": 1,
                    "zoneNumber": 10,
                    "type": "window"
                },
                {
                    "name": "Workout Room",
                    "partition": 1,
                    "zoneNumber": 11,
                    "type": "window"
                },
                {
                    "name": "Utility Room Windows",
                    "partition": 1,
                    "zoneNumber": 12,
                    "type": "window"
                }
            ],
            "_bridge": {
                "username": "*********",
                "port": 54804
            },
            "platform": "Envisalink"

**Comment by dustindclark** [comment]
Your smoke detectors should be wired to your panel just like any other zone, so just create a zone for them. Use `type = "smoke"`  like is shown in the readme. I don't personally have smoke detectors wired to my panel, but there are other users of this plugin who have confirmed that smoke works as expected.

**Comment by dustindclark** [comment]
Closing this out for now. If you need more help, please re-open.

**Comment by scaryfast8750** [comment]
All good.  I got it working using 

 {
                    "name": "Smoke detector",
                    "partition": 1,
                    "type": "smoke"
                }

I didnt know if you could make “smoke 1” and “smoke 2”.  As it turns out, they are all wired to the same circuit so there really isnt a difference per room.

Thank you
