### ISSUE TITLE
Cannot disarm alarm system with the homebridge-envisalink plug-in.

### ISSUE THREAD

**Issue by ghost** [dustindclark/homebridge-envisalink#149]
Hello, 

I cannot disarm alarm using the EnvisaLink plug-in. No probleme arming or using the door, windows or motion sensors. They all seem to respond correctly. 

This function was also not working for me prior to the upgrade to the latest version 1.2.0. 

I have reviewed the documentation in the doc folder, but unfortunatly, I did not find a solution to my issue.

Thank you for your help. 
 

**Logs:**

```
[24/10/2022, 20:20:59] [homebridge-envisalink] Partition 1: ready, mode: undefined.
** Arming system ** [24/10/2022, 20:33:21] [homebridge-envisalink] Partition 1: exitdelay, mode: undefined.
[24/10/2022, 20:35:22] [homebridge-envisalink] Partition 1: specialclosing, mode: undefined.
[24/10/2022, 20:35:22] [homebridge-envisalink] Ignoring status specialclosing. Waiting for armed/armedbypass
[24/10/2022, 20:35:22] [homebridge-envisalink] Partition 1: armed, mode: stay.
** Disarming system ** [24/10/2022, 20:35:35] [homebridge-envisalink] Failed setting panel state to 3 Error: Command 04011 resulted in error from alarm: 025: API Command Invalid Length
    at EnvisalinkHomebridgePlatform.sendAlarmCommand (/var/lib/homebridge/node_modules/homebridge-envisalink/src/platform.ts:480:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at EnvisalinkPartitionAccessory.setPanelState (/var/lib/homebridge/node_modules/homebridge-envisalink/src/partitionAccessory.ts:181:13)
[24/10/2022, 20:36:11] [homebridge-envisalink] Partition 1: useropening, mode: undefined.

```

**Plugin Config:**

    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "host": "1.2.3.4 ",
            "password": "******",
            "pin": "****",
            "port": 4025,
            "proxyPort": 4026,
            "enableVerboseLogging": true,
            "suppressZoneAccessories": false,
            "suppressClockReset": true,
            "policePanic": {
                "enabled": false,
                "name": "Police Panic"
            },
            "ambulancePanic": {
                "enabled": false,
                "name": "Ambulance Panic"
            },
            "firePanic": {
                "enabled": false,
                "name": "Fire Panic"
            },
            "partitions": [
                {
                    "name": "Maison",
                    "enableChimeSwitch": false,
                    "pin": "1"
                }
            ],
            "zones": [
                {
                    "name": "Mouvement Cuisine",
                    "partition": 1,
                    "zoneNumber": 1,
                    "type": "motion"
                },
                {
                    "name": "Porte Entree",
                    "partition": 1,
                    "zoneNumber": 2,
                    "type": "door"
                },
                {
                    "name": "Porte Patio",
                    "partition": 1,
                    "zoneNumber": 3,
                    "type": "door"
                },
                {
                    "name": "Inondation Appartement",
                    "partition": 1,
                    "zoneNumber": 6,
                    "type": "leak"
                },
                {
                    "name": "Porte Salle de Lavage",
                    "partition": 1,
                    "zoneNumber": 7,
                    "type": "door"
                },
                {
                    "name": "Porte de Cote Garage",
                    "partition": 1,
                    "zoneNumber": 10,
                    "type": "door"
                },
                {
                    "name": "Vitre Arriere Garage",
                    "partition": 1,
                    "zoneNumber": 12,
                    "type": "window"
                },
                {
                    "name": "Vitre Cote Arrière Garage",
                    "partition": 1,
                    "zoneNumber": 13,
                    "type": "window"
                },
                {
                    "name": "Vitre Côté Avant Garage",
                    "partition": 1,
                    "zoneNumber": 14,
                    "type": "window"
                },
                {
                    "name": "Porte de Garage",
                    "partition": 1,
                    "zoneNumber": 15,
                    "type": "door"
                },
                {
                    "name": "Porte du Cabanon",
                    "partition": 1,
                    "zoneNumber": 16,
                    "type": "door"
                },
                {
                    "name": "Feu Salon",
                    "partition": 1,
                    "zoneNumber": 18,
                    "type": "smoke"
                },
                {
                    "name": "Feu Cuisine",
                    "partition": 1,
                    "zoneNumber": 19,
                    "type": "smoke"
                },
                {
                    "name": "Feu Salle de Lavage",
                    "partition": 1,
                    "zoneNumber": 20,
                    "type": "smoke"
                },
                {
                    "name": "Feu Garage",
                    "partition": 1,
                    "zoneNumber": 21,
                    "type": "smoke"
                }
            ],
            "_bridge": {
                "username": "*:*:*:*:*:*",
                "port": 35371
            },
            "platform": "Envisalink"
        },

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.2.0
* **Homebridge Version**: Raspbian GNU/Linux Bullseye (11)
* **Node.js Version**: v16.16.0
* **NPM Version**: ??
* **Operating System**: Raspbian 
* **Envisalink 4** : Firmware Version: 01.04.186

**Comment by readylmay** [comment]
Pin on the partition? "1".

Is that right?

On Oct 24, 2022, at 6:13 PM, OnlyMeTwo ***@***.***> wrote:

﻿

Hello,

I cannot disarm alarm using the EnvisaLink plug-in. No probleme arming or using the door, windows or motion sensors. They all seem to respond correctly.

This function was also not working for me prior to the upgrade to the latest version 1.2.0.

I have reviewed the documentation in the doc folder, but unfortunatly, I did not find a solution to my issue.

Thank you for your help.

Logs:

[24/10/2022, 20:20:59] [homebridge-envisalink] Partition 1: ready, mode: undefined.
** Arming system ** [24/10/2022, 20:33:21] [homebridge-envisalink] Partition 1: exitdelay, mode: undefined.
[24/10/2022, 20:35:22] [homebridge-envisalink] Partition 1: specialclosing, mode: undefined.
[24/10/2022, 20:35:22] [homebridge-envisalink] Ignoring status specialclosing. Waiting for armed/armedbypass
[24/10/2022, 20:35:22] [homebridge-envisalink] Partition 1: armed, mode: stay.
** Disarming system ** [24/10/2022, 20:35:35] [homebridge-envisalink] Failed setting panel state to 3 Error: Command 04011 resulted in error from alarm: 025: API Command Invalid Length
    at EnvisalinkHomebridgePlatform.sendAlarmCommand (/var/lib/homebridge/node_modules/homebridge-envisalink/src/platform.ts:480:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at EnvisalinkPartitionAccessory.setPanelState (/var/lib/homebridge/node_modules/homebridge-envisalink/src/partitionAccessory.ts:181:13)
[24/10/2022, 20:36:11] [homebridge-envisalink] Partition 1: useropening, mode: undefined.



Plugin Config:

"platforms": [
    {
        "name": "Config",
        "port": 8581,
        "platform": "config"
    },
    {
        "host": "1.2.3.4 ",
        "password": "******",
        "pin": "****",
        "port": 4025,
        "proxyPort": 4026,
        "enableVerboseLogging": true,
        "suppressZoneAccessories": false,
        "suppressClockReset": true,
        "policePanic": {
            "enabled": false,
            "name": "Police Panic"
        },
        "ambulancePanic": {
            "enabled": false,
            "name": "Ambulance Panic"
        },
        "firePanic": {
            "enabled": false,
            "name": "Fire Panic"
        },
        "partitions": [
            {
                "name": "Maison",
                "enableChimeSwitch": false,
                "pin": "1"
            }
        ],
        "zones": [
            {
                "name": "Mouvement Cuisine",
                "partition": 1,
                "zoneNumber": 1,
                "type": "motion"
            },
            {
                "name": "Porte Entree",
                "partition": 1,
                "zoneNumber": 2,
                "type": "door"
            },
            {
                "name": "Porte Patio",
                "partition": 1,
                "zoneNumber": 3,
                "type": "door"
            },
            {
                "name": "Inondation Appartement",
                "partition": 1,
                "zoneNumber": 6,
                "type": "leak"
            },
            {
                "name": "Porte Salle de Lavage",
                "partition": 1,
                "zoneNumber": 7,
                "type": "door"
            },
            {
                "name": "Porte de Cote Garage",
                "partition": 1,
                "zoneNumber": 10,
                "type": "door"
            },
            {
                "name": "Vitre Arriere Garage",
                "partition": 1,
                "zoneNumber": 12,
                "type": "window"
            },
            {
                "name": "Vitre Cote Arrière Garage",
                "partition": 1,
                "zoneNumber": 13,
                "type": "window"
            },
            {
                "name": "Vitre Côté Avant Garage",
                "partition": 1,
                "zoneNumber": 14,
                "type": "window"
            },
            {
                "name": "Porte de Garage",
                "partition": 1,
                "zoneNumber": 15,
                "type": "door"
            },
            {
                "name": "Porte du Cabanon",
                "partition": 1,
                "zoneNumber": 16,
                "type": "door"
            },
            {
                "name": "Feu Salon",
                "partition": 1,
                "zoneNumber": 18,
                "type": "smoke"
            },
            {
                "name": "Feu Cuisine",
                "partition": 1,
                "zoneNumber": 19,
                "type": "smoke"
            },
            {
                "name": "Feu Salle de Lavage",
                "partition": 1,
                "zoneNumber": 20,
                "type": "smoke"
            },
            {
                "name": "Feu Garage",
                "partition": 1,
                "zoneNumber": 21,
                "type": "smoke"
            }
        ],
        "_bridge": {
            "username": "*:*:*:*:*:*",
            "port": 35371
        },
        "platform": "Envisalink"
    },


Screenshots:

Environment:

  *   Plugin Version: 1.2.0
  *   Homebridge Version: Raspbian GNU/Linux Bullseye (11)
  *   Node.js Version: v16.16.0
  *   NPM Version: ??
  *   Operating System: Raspbian
  *   Envisalink 4 : Firmware Version: 01.04.186

**Comment by ghost** [comment]
Thanks for the info, I guess I missed that one. I update the PIN for the partition 1 and everything is working now.

Thanks ;-)
