### ISSUE TITLE
Punch in code when disarming

### ISSUE THREAD

**Issue by ghost** [dustindclark/homebridge-envisalink#15]
So this is less of an issue and more of a question. Is there a way to code this so that instead of pushing disarm and it disarming the system, that it prompts me to put in my pin code and then disarms? similar to the envisalink app?

**Comment by ToddGreenfield** [comment]
Not currently possible with homekit.

**Comment by dustindclark** [comment]
Homekit implements this security by requiring your iDevice to be unlocked...meaning, Siri will say "you need to unlock your iPhone first".  Closing as a homekit limitation.
