### ISSUE TITLE
2 questions, not really bugs

### ISSUE THREAD

**Issue by guylopes71** [dustindclark/homebridge-envisalink#155]
Hi.  After upgrading today, I get the following messages in the homebridge log

[28/10/2022, 12:27:58] [Envisalink] Partition 1: ready, mode: undefined.
[28/10/2022, 12:34:06] [Envisalink] Partition 1: readyforce, mode: undefined.
[28/10/2022, 12:34:09] [Envisalink] Partition 1: ready, mode: undefined.
[28/10/2022, 12:34:09] [Envisalink] Partition 1: readyforce, mode: undefined.
[28/10/2022, 12:34:11] [Envisalink] Partition 1: ready, mode: undefined.
 and it keeps going forever.  What is this and how can I ''calm'' this?

Second question, I defined which zones I want to see, but for some reason there is an additional zone that transfers to HomeKit, even though it is not setup in the plugin.  any ideas?
thanks, love your work

**Comment by dustindclark** [comment]
Logging is fixed in 1.2.1

Can you post your zone config here and the use case? If you're trying to suppress a contact sensor, it will break bypass capabilities.

**Comment by guylopes71** [comment]
Thanks.  1.2.1 fixed the log!  
for the zone config, not sure if you mean in the plug-in or somewhere else?  I have 16 zones in the alarm system.  In the plug-in, this is the setup I have
![994D6A99-64DF-4E3A-94C9-BC28CA67B8C8](https://user-images.githubusercontent.com/116902544/198833830-1d94e116-f8ad-4a39-807e-db1124cb956b.png)
![CCEAD52F-A40B-4E6F-B23C-28CB6B229FC8](https://user-images.githubusercontent.com/116902544/198833833-36ce1482-71a8-481c-ad29-275491498222.png)
![420E632F-99D6-41F0-AE51-A78BC4859070](https://user-images.githubusercontent.com/116902544/198833834-266e687b-3299-4b3f-ba00-997cb37fbcc7.png)
![9E90BC85-4D0A-48CA-87E1-AA6D4DDF1B07](https://user-images.githubusercontent.com/116902544/198833835-5de1d735-c8f7-4587-8a94-b50ba731eedd.png)
![AEFFA499-FBAA-480B-9EE1-BFB4ECE3FC14](https://user-images.githubusercontent.com/116902544/198833836-d5afbe95-6c9f-4465-8dfb-72a3598def42.png)
![210CA51E-D20A-4A4B-BC97-802B50144589](https://user-images.githubusercontent.com/116902544/198833838-c808f491-62b5-4b94-a545-5d245561f744.png)
![47E323AF-9042-4A2F-9BBB-9AC4A90478CE](https://user-images.githubusercontent.com/116902544/198833840-d6c5d86f-6f30-4b5b-8a78-9e4f90c1f55d.png)

**Comment by guylopes71** [comment]
Hi.  So from the screenshots you can see the zones I am monitoring and sending to HomeKit.  They all work fine, but I did not configure zone5 as you can see in the screenshots, but it shows up in HomeKit and is reacting correctly to the real zone5 for the alarm system.

**Comment by guylopes71** [comment]
Hi, regarding zone5, I cleared it from homebridge Cache and it is now gone! Thanks

**Comment by dustindclark** [comment]
Ok great! Glad to hear it's working.
