### ISSUE TITLE
Allow Disabling Alarm Bypass Switch Using Config

### ISSUE THREAD

**Issue by raphaeldavid** [dustindclark/homebridge-envisalink#156]
There's a way to remove the Alarm bypass switch ?

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 1.5.1
* **Node.js Version**: 16.18.0
* **NPM Version**: 
* **Operating System**: Ubuntu  Docker on Unraid

**Comment by dustindclark** [comment]
There's currently not a way. What's the reason that you'd like it removed? It's there if you need it, but you can leave it off if you don't.

**Comment by dustindclark** [comment]
No response. Closing. Reopen with details about the ask if necessary.
