### ISSUE TITLE
Verbose Logging not Working

### ISSUE THREAD

**Issue by readylmay** [dustindclark/homebridge-envisalink#157]
When reviewing Homebridge logs (usually in the UI console) - envisalink logs are not shown. The only entries are:

```
[29/10/2022, 13:34:51] [Envisalink] Envisalink login requested... sending response...
[29/10/2022, 13:34:51] [Envisalink] Envisalink successfully logged in!  getting current data...
```

Verbose is set to true. 

**To Reproduce:**
Set verbose logging to true and review logs.

**Expected behavior:**
Verbose logging entries will be available in the log.

**Logs:**

No logs available. 

**Plugin Config:**

```
"host": "10.10.1.54",
            "password": "user",
            "pin": "xxxx",
            "port": 4025,
            "proxyPort": 4026,
            "enableVerboseLogging": true,
            "suppressZoneAccessories": false,
            "suppressClockReset": false,
```

**Screenshots:**

**Environment:**

* **Plugin Version**:1.2.1
* **Homebridge Version**: 1.5.1
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**: Raspbian

**Comment by dustindclark** [comment]
Do you have Homebridge debug enabled? Both are required for verbose logging.DustinSent from my iPhoneOn Oct 29, 2022, at 3:43 PM, readylmay ***@***.***> wrote:﻿

When reviewing Homebridge logs (usually in the UI console) - envisalink logs are not shown. The only entries are:
[29/10/2022, 13:34:51] [Envisalink] Envisalink login requested... sending response...
[29/10/2022, 13:34:51] [Envisalink] Envisalink successfully logged in!  getting current data...

Verbose is set to true.

To Reproduce:
Set verbose logging to true and review logs.
Expected behavior:
Verbose logging entries will be available in the log.
Logs:
No logs available.
Plugin Config:
"host": "10.10.1.54",
            "password": "user",
            "pin": "xxxx",
            "port": 4025,
            "proxyPort": 4026,
            "enableVerboseLogging": true,
            "suppressZoneAccessories": false,
            "suppressClockReset": false,

Screenshots:

Environment:

Plugin Version:1.2.1
Homebridge Version: 1.5.1
Node.js Version: 
NPM Version: 
Operating System: Raspbian

**Comment by readylmay** [comment]
Yes, I do.

On Oct 30, 2022, at 9:02 AM, Dustin Clark ***@***.***> wrote:

﻿

Do you have Homebridge debug enabled? Both are required for verbose logging.DustinSent from my iPhoneOn Oct 29, 2022, at 3:43 PM, readylmay ***@***.***> wrote:﻿

When reviewing Homebridge logs (usually in the UI console) - envisalink logs are not shown. The only entries are:
[29/10/2022, 13:34:51] [Envisalink] Envisalink login requested... sending response...
[29/10/2022, 13:34:51] [Envisalink] Envisalink successfully logged in! getting current data...

Verbose is set to true.

To Reproduce:
Set verbose logging to true and review logs.
Expected behavior:
Verbose logging entries will be available in the log.
Logs:
No logs available.
Plugin Config:
"host": "10.10.1.54",
"password": "user",
"pin": "xxxx",
"port": 4025,
"proxyPort": 4026,
"enableVerboseLogging": true,
"suppressZoneAccessories": false,
"suppressClockReset": false,

Screenshots:

Environment:

Plugin Version:1.2.1
Homebridge Version: 1.5.1
Node.js Version:
NPM Version:
Operating System: Raspbian

**Comment by readylmay** [comment]
Ah, sorry - I do not. Fixed.

On Oct 30, 2022, at 9:02 AM, Dustin Clark ***@***.***> wrote:

﻿

Do you have Homebridge debug enabled? Both are required for verbose logging.DustinSent from my iPhoneOn Oct 29, 2022, at 3:43 PM, readylmay ***@***.***> wrote:﻿

When reviewing Homebridge logs (usually in the UI console) - envisalink logs are not shown. The only entries are:
[29/10/2022, 13:34:51] [Envisalink] Envisalink login requested... sending response...
[29/10/2022, 13:34:51] [Envisalink] Envisalink successfully logged in! getting current data...

Verbose is set to true.

To Reproduce:
Set verbose logging to true and review logs.
Expected behavior:
Verbose logging entries will be available in the log.
Logs:
No logs available.
Plugin Config:
"host": "10.10.1.54",
"password": "user",
"pin": "xxxx",
"port": 4025,
"proxyPort": 4026,
"enableVerboseLogging": true,
"suppressZoneAccessories": false,
"suppressClockReset": false,

Screenshots:

Environment:

Plugin Version:1.2.1
Homebridge Version: 1.5.1
Node.js Version:
NPM Version:
Operating System: Raspbian

**Comment by readylmay** [comment]
Config error.
