### ISSUE TITLE
Issue with disarming

### ISSUE THREAD

**Issue by scaryfast8750** [dustindclark/homebridge-envisalink#158]
On v1.2.1 the motion sensors all work. But the the alarm on/off doesn’t reflect true state of the alarm. When the alarm is on. HomeKit tile just says disarming.

**Comment by readylmay** [comment]
I've noticed this too, will try to find steps to repro.

**Comment by dustindclark** [comment]
Ran into a situation tonight where the HomeKit thought the panel was armed (or arming), but it wasn't. Had to disarm and re-arm to workaround. Potentially related to [this commit](https://github.com/dustindclark/homebridge-envisalink/commit/ffbcf493aa05bf3087dafd7b7528ab44ae292bef), which fixes duplicate notifications.

**Comment by scaryfast8750** [comment]
@dustindclark what can I provide you to help track this down?  Do you need debug log entries?

I can reproduce this by setting the alarm with the alarm keypad on Homebridge 1.5.1 with Envisalink plugin 1.2.1.  When you open HomeKit to try to disarm, it says "disarming" and will never stop.  If you disarm with the panel, HomeKit gets the proper notification that the alarm was disabled.


1.  you set alarm from HomeKit - you can disable from HomeKit also
2. If No alarm is set, the homekit status is reflected properly.

Let us know how we can help and Thank you.

**Comment by dustindclark** [comment]
Does this happen on version 1.1.1 of the plugin?

**Comment by scaryfast8750** [comment]
used “install alternate version” to downgrade to plug-in 1.1.1 with homebridge 1.5.1 and it works correctly. Set alarm with keypad, HomeKit updates appropriately. Disarmed with HomeKit worked perfect. On Nov 4, 2022, at 7:00 PM, Dustin Clark ***@***.***> wrote:﻿
Does this happen on version 1.1.1 of the plugin?

**Comment by dustindclark** [comment]
This should be fixed in 1.2.7. Please re-open if you still see this after upgrading.
