### ISSUE TITLE
fucntion of on/off switch in Homekit

### ISSUE THREAD

**Issue by guylopes71** [dustindclark/homebridge-envisalink#166]
HI.  Love your plugin, working great!

1 question:  what does the on/off switch next to the arming modes do?  I seem to be able to arm when it is on or off, so I dont quite get what it does.

thanks for sheeding some light!

**Comment by dustindclark** [comment]
This is discussed in the latest [release notes](https://github.com/dustindclark/homebridge-envisalink/releases/tag/v1.2.0). Re-open if you still have questions. Thanks.

**Comment by guylopes71** [comment]
Thanks, did not understand it that way, but re-reading it now under context, all clear and good!Sent from my iPhoneOn Nov 10, 2022, at 2:01 PM, Dustin Clark ***@***.***> wrote:﻿
This is discussed in the latest release notes. Re-open if you still have questions. Thanks.
