### ISSUE TITLE
Ability to specify particular zones to include

### ISSUE THREAD

**Issue by durosity** [dustindclark/homebridge-envisalink#17]
It’d be great if I could just specify the zones rather than having to list each individual zone even if not used.  EG in the config file being able to have entries like:

      "zones": [
        {
          "name": "Front Door",
          "type": "door",
          “partition”: 1
          “zone”: 1
        },
        {
          "name": "Master Bedroom Door",
          "type": "door",
          “partition": 1
          “zone”: 7
        },

**Comment by scotteby** [comment]
I had this requirement as well because my installer skipped zone numbers when programming my system. It required 1 line of code to be changed:

```javascript
//this.platformAccessories.push(new EnvisalinkAccessory(this.log, zone.type, zone, zone.partition, i + 1));
this.platformAccessories.push(new EnvisalinkAccessory(this.log, zone.type, zone, zone.partition, zone.number));
```

I added a number attribute to the config file:

```json
       {
         "name": "Garage Back Door",
          "type": "door",
          "partition": 1,
          "number": 5
       },
       {
         "name": "Front Door",
          "type": "door",
          "partition": 1,
	  "number": 9
       }
```

Something like this would be even better now that I look at it:

```javascript
zone.number ? zone.number : i + 1
```
