### ISSUE TITLE
DSC + Envisalink + homebridge

### ISSUE THREAD

**Issue by ageorgios** [dustindclark/homebridge-envisalink#18]
Hello,
as a homebridge user I am planning to buy a DSC+Envisalink combination for my alarm system.

reading this:
https://diysecurityguy.wordpress.com/2015/09/08/review-envisalink-evl-3/
says:
If you are interested in the TPI for home automation, be wary of the severe limitation that it won’t report zones on your Vista panel when armed. **So once you arm the system, any automation that uses your alarm panel will stop working.**

Is this correct for DSC panels?

Thank you.

**Comment by ToddGreenfield** [comment]
This is not accurate for DSC systems. I run a DSC PowerSeries 1864 using an EVL-4 and the motion sensors (wireless) do report status changes while armed. I just tested again to be sure and it worked fine. Using this plugin and the Elgato Eve app I saw the state change. I also saw the update in AllSecure (iOS app) which shows last time breached.
Two points to note though using wireless motion sensors- 1) there is a 6 second delay after motion is detected before the device sends notice to the panel; and 2) there is a feature to help preserve battery life called High Traffic Shutdown Mode - which will not re-transmit status changes within a 3 minute window. 
Good luck!
