### ISSUE TITLE
Bypass support 

### ISSUE THREAD

**Issue by brennan-babb** [dustindclark/homebridge-envisalink#286]
**Describe The Bug:**
I am trying to implement the zone bypass feature and getting envisalink issues and error messages as per below
I have an envisalink 4 on a DSC alarm
Bypass works with eyezon

**To Reproduce:**
Enable Zonebypass in homekit or  Homebridge
slide homekit zone to "night" or "home" and below logs occur.

**Expected behaviour:**
I expect no error message  as per below
I expected the outside Zone 2 security beams to be enabled

**Logs:**

```
[11/06/2023, 23:31:20] [Envisalink] setBypassActive to true for partition 2
[11/06/2023, 23:31:24] [Envisalink] 0 open zones were bypassed.
[11/06/2023, 23:31:24] [Envisalink] Failed setting panel state to 0 Error: Command 0312 resulted in error from alarm: 024: API System Not Ready to Arm (system is either not-secure, in exit-delay, or already armed)
    at EnvisalinkHomebridgePlatform.sendAlarmCommand (/usr/lib/node_modules/homebridge-envisalink/src/platform.ts:483:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at EnvisalinkPartitionAccessory.setPanelState (/usr/lib/node_modules/homebridge-envisalink/src/partitionAccessory.ts:213:13)
[11/06/2023, 23:31:26] [Envisalink] Failed setting panel state to 3 Error: Command 04021256 resulted in error from alarm: 023: API System Not Armed (sent in response to a disarm command)
    at EnvisalinkHomebridgePlatform.sendAlarmCommand (/usr/lib/node_modules/homebridge-envisalink/src/platform.ts:483:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at EnvisalinkPartitionAccessory.setPanelState (/usr/lib/node_modules/homebridge-envisalink/src/partitionAccessory.ts:213:13)
[11/06/2023, 23:31:30] [Envisalink] 0 open zones were bypassed.
[11/06/2023, 23:31:30] [Envisalink] Failed setting panel state to 2 Error: Command 0322 resulted in error from alarm: 024: API System Not Ready to Arm (system is either not-secure, in exit-delay, or already armed)
    at EnvisalinkHomebridgePlatform.sendAlarmCommand (/usr/lib/node_modules/homebridge-envisalink/src/platform.ts:483:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at EnvisalinkPartitionAccessory.setPanelState (/usr/lib/node_modules/homebridge-envisalink/src/partitionAccessory.ts:213:13)
[11/06/2023, 23:
```

```json
{
            "host": "192.168.1.15",
            "password": "xxxxx",
            "pin": "xxxx",
            "port": 4025,
            "proxyPort": 4026,
            "enableVerboseLogging": false,
            "suppressZoneAccessories": false,
            "suppressClockReset": false,
            "policePanic": {
                "enabled": false,
                "name": "Police Panic"
            },
            "ambulancePanic": {
                "enabled": false,
                "name": "Ambulance Panic"
            },
            "firePanic": {
                "enabled": false,
                "name": "Fire Panic"
            },
            "partitions": [
                {
                    "name": "Inside Alarm",
                    "enableChimeSwitch": false
                },
                {
                    "name": "Outside Beams",
                    "enableChimeSwitch": true
                }
            ],
            "zones": [
                {
                    "name": "Main Bedroom Sensor",
                    "partition": 1,
                    "type": "motion"
                },
                {
                    "name": "Zane's Bedroom Sensor",
                    "partition": 1,
                    "type": "motion"
                },
                {
                    "name": "Trenton's Bedroom Sensor",
                    "partition": 1,
                    "type": "motion"
                },
                {
                    "name": "Lounge Sensor",
                    "partition": 1,
                    "type": "motion"
                },
                {
                    "name": "Sliding Door Lounge",
                    "partition": 1,
                    "type": "door"
                },
                {
                    "name": "Atrium Door",
                    "partition": 1,
                    "type": "door"
                },
                {
                    "name": "Guest suite Sensor",
                    "partition": 1,
                    "type": "motion"
                },
                {
                    "name": "Entrance Room Sensor ",
                    "partition": 1,
                    "type": "motion"
                },
                {
                    "name": "Scullery Motion Sensor",
                    "partition": 1,
                    "type": "motion"
                },
                {
                    "name": "Scullery door",
                    "partition": 1,
                    "type": "door"
                },
                {
                    "name": "Front door Sensor",
                    "partition": 1,
                    "type": "motion"
                },
                {
                    "name": "Front Door",
                    "partition": 1,
                    "type": "door"
                },
                {
                    "name": "Study Sensor",
                    "partition": 1,
                    "type": "motion"
                },
                {
                    "name": "unknown24 Sensor",
                    "partition": 1,
                    "type": "motion"
                },
                {
                    "name": "Outside Front Door Sensor",
                    "partition": 2,
                    "type": "motion"
                },
                {
                    "name": "Garage inside Sensor",
                    "partition": 2,
                    "type": "motion"
                },
                {
                    "name": "Trash Area Sensor",
                    "partition": 2,
                    "type": "motion"
                },
                {
                    "name": "Jaccuzi Sensor",
                    "partition": 2,
                    "type": "motion"
                },
                {
                    "name": "Patio Sensor",
                    "partition": 2,
                    "type": "motion"
                },
                {
                    "name": "Corner Outside PIR ",
                    "partition": 2,
                    "type": "motion"
                },
                {
                    "name": "boys Window PIR",
                    "partition": 2,
                    "type": "motion"
                }
            ],
            "platform": "Envisalink"


**Environment:**

* **Plugin Version**:  v1.2.10
* **Homebridge Version**:   v1.6.1
* **Node.js Version**: v18.16.0
* **NPM Version**:  9.5.1
* **Operating System**:  Raspbian 
* DSC alarm panel
* ENvisalink 4 (eyezon keeps firmware up to date)

**Comment by dustindclark** [comment]
The bypass feature currently only bypasses open doors and windows. I'm unfamiliar with "beams".DustinSent from my iPhoneOn Jun 11, 2023, at 16:59, brennan-babb ***@***.***> wrote:﻿
Describe The Bug:
I am trying to implement the zone bypass feature and getting envisalink issues and error messages as per below
I have an envisalink 4 on a DSC alarm
Bypass works with eyezon
To Reproduce:
Enable Zonebypass in homekit or  Homebridge
slide homekit zone to "night" or "home" and below logs occur.
Expected behaviour:
I expect no error message  as per below
I expected the outside Zone 2 security beams to be enabled
Logs:
[11/06/2023, 23:31:20] [Envisalink] setBypassActive to true for partition 2
[11/06/2023, 23:31:24] [Envisalink] 0 open zones were bypassed.
[11/06/2023, 23:31:24] [Envisalink] Failed setting panel state to 0 Error: Command 0312 resulted in error from alarm: 024: API System Not Ready to Arm (system is either not-secure, in exit-delay, or already armed)
    at EnvisalinkHomebridgePlatform.sendAlarmCommand (/usr/lib/node_modules/homebridge-envisalink/src/platform.ts:483:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at EnvisalinkPartitionAccessory.setPanelState (/usr/lib/node_modules/homebridge-envisalink/src/partitionAccessory.ts:213:13)
[11/06/2023, 23:31:26] [Envisalink] Failed setting panel state to 3 Error: Command 04021256 resulted in error from alarm: 023: API System Not Armed (sent in response to a disarm command)
    at EnvisalinkHomebridgePlatform.sendAlarmCommand (/usr/lib/node_modules/homebridge-envisalink/src/platform.ts:483:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at EnvisalinkPartitionAccessory.setPanelState (/usr/lib/node_modules/homebridge-envisalink/src/partitionAccessory.ts:213:13)
[11/06/2023, 23:31:30] [Envisalink] 0 open zones were bypassed.
[11/06/2023, 23:31:30] [Envisalink] Failed setting panel state to 2 Error: Command 0322 resulted in error from alarm: 024: API System Not Ready to Arm (system is either not-secure, in exit-delay, or already armed)
    at EnvisalinkHomebridgePlatform.sendAlarmCommand (/usr/lib/node_modules/homebridge-envisalink/src/platform.ts:483:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at EnvisalinkPartitionAccessory.setPanelState (/usr/lib/node_modules/homebridge-envisalink/src/partitionAccessory.ts:213:13)
[11/06/2023, 23:

{
            "host": "192.168.1.15",
            "password": "xxxxx",
            "pin": "xxxx",
            "port": 4025,
            "proxyPort": 4026,
            "enableVerboseLogging": false,
            "suppressZoneAccessories": false,
            "suppressClockReset": false,
            "policePanic": {
                "enabled": false,
                "name": "Police Panic"
            },
            "ambulancePanic": {
                "enabled": false,
                "name": "Ambulance Panic"
            },
            "firePanic": {
                "enabled": false,
                "name": "Fire Panic"
            },
            "partitions": [
                {
                    "name": "Inside Alarm",
                    "enableChimeSwitch": false
                },
                {
                    "name": "Outside Beams",
                    "enableChimeSwitch": true
                }
            ],
            "zones": [
                {
                    "name": "Main Bedroom Sensor",
                    "partition": 1,
                    "type": "motion"
                },
                {
                    "name": "Zane's Bedroom Sensor",
                    "partition": 1,
                    "type": "motion"
                },
                {
                    "name": "Trenton's Bedroom Sensor",
                    "partition": 1,
                    "type": "motion"
                },
                {
                    "name": "Lounge Sensor",
                    "partition": 1,
                    "type": "motion"
                },
                {
                    "name": "Sliding Door Lounge",
                    "partition": 1,
                    "type": "door"
                },
                {
                    "name": "Atrium Door",
                    "partition": 1,
                    "type": "door"
                },
                {
                    "name": "Guest suite Sensor",
                    "partition": 1,
                    "type": "motion"
                },
                {
                    "name": "Entrance Room Sensor ",
                    "partition": 1,
                    "type": "motion"
                },
                {
                    "name": "Scullery Motion Sensor",
                    "partition": 1,
                    "type": "motion"
                },
                {
                    "name": "Scullery door",
                    "partition": 1,
                    "type": "door"
                },
                {
                    "name": "Front door Sensor",
                    "partition": 1,
                    "type": "motion"
                },
                {
                    "name": "Front Door",
                    "partition": 1,
                    "type": "door"
                },
                {
                    "name": "Study Sensor",
                    "partition": 1,
                    "type": "motion"
                },
                {
                    "name": "unknown24 Sensor",
                    "partition": 1,
                    "type": "motion"
                },
                {
                    "name": "Outside Front Door Sensor",
                    "partition": 2,
                    "type": "motion"
                },
                {
                    "name": "Garage inside Sensor",
                    "partition": 2,
                    "type": "motion"
                },
                {
                    "name": "Trash Area Sensor",
                    "partition": 2,
                    "type": "motion"
                },
                {
                    "name": "Jaccuzi Sensor",
                    "partition": 2,
                    "type": "motion"
                },
                {
                    "name": "Patio Sensor",
                    "partition": 2,
                    "type": "motion"
                },
                {
                    "name": "Corner Outside PIR ",
                    "partition": 2,
                    "type": "motion"
                },
                {
                    "name": "boys Window PIR",
                    "partition": 2,
                    "type": "motion"
                }
            ],
            "platform": "Envisalink"


**Environment:**

* **Plugin Version**:  v1.2.10
* **Homebridge Version**:   v1.6.1
* **Node.js Version**: v18.16.0
* **NPM Version**:  9.5.1
* **Operating System**:  Raspbian 
* DSC alarm panel
* ENvisalink 4 (eyezon keeps firmware up to date)

**Comment by brennan-babb** [comment]
Beams are motion sensors for movement. On or off. ... open or closed. 
Same thing as a door sensor. on or off.
Any Idea what I can try to mitigate these issues.

**Comment by brennan-babb** [comment]
Can I share any other info to find the issues?

**Comment by dustindclark** [comment]
The existing bypass support will only bypass _open_ zones when you try to arm. It will not bypass zones that are closed. To support this, you need to be able to manually bypass these zones rather than a single bypass switch. I've re-opened #56 to track this, but likely will not have time to add this enhancement any time soon. Feel free to re-open this ticket if you think there's some other solution for bypassing beams.
