### ISSUE TITLE
EVL 3 and using Siri to set alarm to Home

### ISSUE THREAD

**Issue by jeffcohen-ai** [dustindclark/homebridge-envisalink#292]
**Describe Your Problem:**
When using Siri I can set the alarm to away when I say 
Siri arm home alarm.  However, I cannot figure out how to use Siri to set the alarm to Home.  

**Logs:**
No Logs
```
Show the Homebridge logs here, remove any sensitive information.
No logs

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by jeffcohen-ai** [comment]
Thank you!

**Comment by dustindclark** [comment]
This is a HomeKit limitation...lots of Reddit threads on this (i.e. https://www.reddit.com/r/HomeKit/comments/spnvw1/need_help_figuring_out_the_siri_commands_for_home/). You may have more luck if you name your alarm something like "Security System" to disambiguate with setting timers/alarms. Personally, I use scenes. For example, my Good Night scene sets the alarm to Home and turns off all the lights. Then just say "Siri, good night"

**Comment by jeffcohen-ai** [comment]
thank you.  that is a great way of going about it.
