### ISSUE TITLE
DSC fails to Disarm - Bad Checksum Received

### ISSUE THREAD

**Issue by dgburtonbv** [dustindclark/homebridge-envisalink#3]
Thanks for your work on this plugin!

I'm hoping you can help with this: I'm using iOS10 Beta 3 and whenever I select "Off" I see the following in the Homebridge log (and the panel doesn't disarm):

[7/20/2016, 6:54:06 PM] Partition status changed to: { partition: 1, code: '652', mode: '1' }
Set status on accessory Alarm to {"name":"Partition Armed","pre":"Partition","bytes":1,"post":"is Armed","send":"armed","action":"updatepartition"}
[7/20/2016, 6:54:22 PM] Attempting to set alarm state to: 3
[7/20/2016, 6:54:22 PM] Disarming alarm with PIN.
sendcommand 040110048a
manual command callback
Bad Checksum Received

![22c891a8-edc8-45e9-9437-68c58b462c8d](https://cloud.githubusercontent.com/assets/6538860/16997781/d1799e90-4eae-11e6-84f9-354a0bbdec4b.JPG)

**Comment by pakerfeldt** [comment]
I don't know much about homebridge but I do know however that EnvisaLink expects checksum to be in uppercase. If the command would have said 8A (instead of 8a) you wouldn't get the checksum error back.

**Comment by dgburtonbv** [comment]
Thanks @pakerfeldt - I'll try that and see if it fixes it.

**Comment by pakerfeldt** [comment]
I just sent a pull request to NodeAlarmProxy with that fix, see commit above.

**Comment by dgburtonbv** [comment]
Thanks!

**Comment by dustindclark** [comment]
This duplicates #1 (is pending an upstream dependency).  Closing.
