### ISSUE TITLE
Alarm Status Not updating

### ISSUE THREAD

**Issue by lfiocco** [dustindclark/homebridge-envisalink#30]
Hello, great app. If I reboot the pi, the status of the alarm shows off. When it’s On. I have to reboot a few times to get it working, or set alarm to home, then off.

**Comment by dstapleton92** [comment]
Hi! I'm working on a re-write of this plugin that will resolve this as well as many other issues (Problems after alarm has triggered, or smoke detector triggered). I'm about 90% finished with it.

**Comment by lfiocco** [comment]
Nice, and thank you.

Sent from my iPhone

On Jan 29, 2018, at 11:28 AM, dstapleton92 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi! I'm working on a re-write of this plugin that will resolve this as well as many other issues (Problems after alarm has triggered, or smoke detector triggered). I'm about 90% finished with it.

**Comment by peros550** [comment]
Hey @dstapleton92 , any news on the update?

**Comment by dstapleton92** [comment]
Hi @peros550 I think it's done. I haven't had any time to dedicate for testing, so I'm hesitant to open a Pull Request just yet. If you'd like to test it (please put it through the wringer and try to "break" it), you can find it [here](https://github.com/dstapleton92/homebridge-envisalink). It's written in ES6 and uses Babel to transpile. Make sure you read the note for developers I added at the bottom of the README file. (Mainly, `npm install`, then `npm run build` to create the compiled JS files that will work with Node/Homebridge.

**Comment by dustindclark** [comment]
Fixed, verified, and published in v0.2.14 thanks to @rafiqsarlie.
