### ISSUE TITLE
Support Custom Commands

### ISSUE THREAD

**Issue by brownjd** [dustindclark/homebridge-envisalink#32]
I would like to create a button for enabling and disabling the door chime. The command is '*4'. I'd love to be able to have a toggle or simply a button (like an accessory) that would send that code to the Envisalink. I don't see an example of the syntax for sending custom sequences in the config.json.

**Comment by dstapleton92** [comment]
What an interesting idea! I’m working on some updates and just might include that. With what’s currently possible in homekit, here’s what I could do:
- Have something in config.json like enableChimeToggle: true
- If that toggle is enabled, a Stateful Programmable Switch will be added as an accessory (will look like a light switch). That switch will allow toggling the chime on and off.

**Comment by dstapleton92** [comment]
Actually, forget about the switch. It could manifest itself as a speaker with a mute control.

**Comment by peros550** [comment]
A switch can be automated. You could have it on during daytime and off during night. 

Do you know if  a speaker’s mute function can be part of an automation ?

**Comment by ToddGreenfield** [comment]
The mute function can be used as a trigger with automations but cannot be set up using the Home App. You would need to use something like Eve to set it up.

**Comment by brownjd** [comment]
One issue I think with this is that I don't think you can query the envisalink for door chime status. *4 toggles it off and on, but the only way you know what state it is in after sending the command is from the audible tone emitted from the keypad. It is still desirable to be able to toggle it, but it would complicate scheduling it since you don't know what state you are starting from if someone inadvertently sets it during the day.

**Comment by brownjd** [comment]
I know others use custom sequences, so it would be nice to have a generic interface to define buttons for custom sequences of commands. <sequence name="Door Chime" value="*4" style="Button"/>
You can go further and have a stateful attribute with a query sequence that would return true or false for the button state (if that is even supported by envisalink - I have no idea).

**Comment by dstapleton92** [comment]
The Envisalink TPI sends separate events for Chime Enabled and Chime Disabled. So we could keep up with the state even if it is toggled during the day. The only issue is that there would be no way to get the chime status when homebridge first starts up. Might just have to assume chime enabled, and then you can disable/enable it yourself. After that, the plugin would be able to keep in sync.

**Comment by brownjd** [comment]
On startup, it could send a *4 to discover the state and then set it back.

**Comment by dustindclark** [comment]
Closing in favor of https://github.com/dustindclark/homebridge-envisalink/issues/81.
