### ISSUE TITLE
Homebridge Reports Inaccurate Alarm State, Crashes When Attempting to Set State

### ISSUE THREAD

**Issue by amanofcharacter** [dustindclark/homebridge-envisalink#34]
I had a previous issue getting my config.json to be recognized. It was just my noobish ignorance. That was here: https://github.com/dustindclark/homebridge-envisalink/issues/33

I got the config working, and my Alarm plus all sensors seems to be accurately listed in the Apple Home app now. However, the Alarm start always initially loads as "Off", whether it's _actually_ off or armed, at the time the I start Homebridge. When I attempt to set the Alarm to Home, Away, or Night, Homebridge appears to crash:

(Note: the following paste includes the initial terminal lines when I actually start Homebridge. I'm not sure what the "actual connected" and "actual disconnected" lines mean during the startup. Is this relevant? Beginning with the "Attempting to set alarm..." line is where I've pressed the button to set the state, and Homebridge crashed.)

[2018-2-9 09:51:45] Homebridge is running on port 51826.
server bound
actual connected
[2018-2-9 09:51:50] [Envisalink] Setting the current time on the alarm system to: 0951020918
sendcommand 010095102091894
actual disconnected
[2018-2-9 09:59:54] [Envisalink] Attempting to set alarm state to:  0
[2018-2-9 09:59:54] [Envisalink] Arming alarm to Stay/Night.
sendcommand 0311C5
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:356:12)
    at sendcommand (/usr/local/lib/node_modules/homebridge-envisalink/node_modules/nodealarmproxy/nodealarmproxy.js:253:12)
    at Object.exports.manualCommand (/usr/local/lib/node_modules/homebridge-envisalink/node_modules/nodealarmproxy/nodealarmproxy.js:263:3)
    at EnvisalinkAccessory.processAlarmState (/usr/local/lib/node_modules/homebridge-envisalink/index.js:433:17)
    at EnvisalinkAccessory.processDelayedEvents (/usr/local/lib/node_modules/homebridge-envisalink/index.js:521:18)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)

P.S. - I'm pretty sure I'm using a Honeywell Vista 20p panel, not a DSC. Could this be a problem?

**Comment by IMNotMax** [comment]
If you’re using a Honeywell did you change your config.json to specify HoneyWell ?

**Comment by IMNotMax** [comment]
Do you have another device or server accessing your alarm ? Can you log in the web interface of your alarm with the login/pwd used in the config.json ? Did you activate the “Enable TPI Session Alerts” in the network section of the web interface ?

**Comment by JustinDavidMartin** [comment]
I did try setting the config to HoneyWell, but I think that was before I got the config.json on the right place. I'll try it again. I don't believe I have any other device accessing the EVL, but I do have AllSecure setup on my iphone, both local and remote.

I did not have the TPI Session Alerts enabled, I'll login now and turn it on, then change DSC to HoneyWell in the config.

**Comment by JustinDavidMartin** [comment]
So enabled TPI session alerts, but it still always shows "offline", and "no client". Is that correct?

![image](https://user-images.githubusercontent.com/33995108/35998610-09f97d3e-0cd2-11e8-9f80-d7a003372060.png)

I also changed my config.json to type "HoneyWell":

"platforms": [{
		"platform": "Envisalink",
		"host": "192.168.1.xxx",
		"deviceType": "HoneyWell",
		"password": "******",
		"pin": "****",

Still no success. Homebridge still crashes when attempting to arm. It also still doesn't report the correct state, or report opening/closing of the zones.

[2018-2-9 11:13:08] [Envisalink] Attempting to set alarm state to:  0
[2018-2-9 11:13:08] [Envisalink] Arming alarm to Stay/Night.
sendcommand 0311C5
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:356:12)
    at sendcommand (/usr/local/lib/node_modules/homebridge-envisalink/node_modules/nodealarmproxy/nodealarmproxy.js:253:12)
    at Object.exports.manualCommand (/usr/local/lib/node_modules/homebridge-envisalink/node_modules/nodealarmproxy/nodealarmproxy.js:263:3)
    at EnvisalinkAccessory.processAlarmState (/usr/local/lib/node_modules/homebridge-envisalink/index.js:433:17)
    at EnvisalinkAccessory.processDelayedEvents (/usr/local/lib/node_modules/homebridge-envisalink/index.js:521:18)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)

**Comment by JustinDavidMartin** [comment]
I searched other issues (didn't see the closed issues tab before), and I found that someone had the exact same issue that I had: https://github.com/dustindclark/homebridge-envisalink/issues/27

I forgot to mention that for me as well, like this other user, I noticed that in the Home App, but alarm was displaying "Obstruction Detected", when this was not the case. So I believe it's the same issue. This user seemed to resolve their issue by finding another device. a Vera Home Controller, that was also accessing the EVL.

Strangely, I don't have any other devices accessing my EVL... None that I'm aware of. I have AllSecure setup on my iPhone, does this count? I also have the Eyez On website all setup as usual, if I was using the EVL with only Eyez On access, does this count?

Does anyone have any ideas what my issue could be?

**Comment by dstapleton92** [comment]
After looking over the plugin’s code, and the code of NodeAlarmProxy, which this plugin utilizes to communicate with the Envisalink, I really don’t understand how it could possibly be Honeywell compatible. The API for the Ademco/Honeywell version of the Envisalink is completely and radically different.

I know the readme says it should work, but I really don’t see how. Can anyone confirm if it has ever worked? The default state of this code reports disarmed and all zones closed. Barring any communication with the panel, that is what you would see. Have you tried opening a door or window to see if it updates in the Home app?

But that is definitely why it is crashing. This plugin sends the TPI command for arm away (031) and the Envisalink/node alarm proxy disconnects because that command is invalid for ademco.

**Comment by JustinDavidMartin** [comment]
Hi, thanks for commenting. Yes, I tried opening and closing my front door, and there was no change on the homekit sensor indicator.

That’s a real shame about the compatibility, I was pretty excited to get this setup. Is remotely feasible for the plugin to be modified to work with the Honeywell/Ademco models? Like is it simply a matter of swapping out codes to send in the plugin? Or is it way more complicated than that?

**Comment by dstapleton92** [comment]
It’s pretty involved. Not impossible, but also not easy. The changes would actually have to start over at Node Alarm Proxy. The main issue is that the standard Envisalink TPI for DSC is very granular (many, specific codes sent in response to specific events). The TPI for Honey/Ademco has only a few actions and events, and all the data is “clumped” together. 

But like I said, Node Alarm Proxy would have to be changed first, because it receives the TPI codes and dispatches the events that this plugin listens for.

**Comment by dustindclark** [comment]
Closing as dupe in favor of #59.
