### ISSUE TITLE
Garage Door Opener using DSC PGM

### ISSUE THREAD

**Issue by tz8p05** [dustindclark/homebridge-envisalink#36]
What would be really cool is adding an accessory which controls a garage door switch (either directly or via a relay, using PGM) and get the door open/close status via two reed switches/sensors. I have been looking at doing this:
https://www.npmjs.com/package/homebridge-rasppi-gpio-garagedoor
I am quite comfortable  using RPi/linux but my Pi died on me while setting this up, so was looking at alternatives. But I think it would be great is we could do it via DSC. Not really an issue but a polite feature request :)

**Comment by dustindclark** [comment]
Unrelated to Envisalink.  You may check [homebridge-globalcache-itach](https://www.npmjs.com/package/homebridge-globalcache-itach), which is another one of my plugins that I've used previously for my garage door.  It works with [globalcache itach](https://www.globalcache.com/products/itach/) (wifi or wired)
