### ISSUE TITLE
Looking for testers

### ISSUE THREAD

**Issue by dstapleton92** [dustindclark/homebridge-envisalink#38]
Hi everyone. I think I'm pretty much finished with my updates for this plugin. But before I open a pull request, I need your help! Any tinkerers/developers out there, please download my version of the plugin and test it out- put it through the wringer and try to break it. The main thing I haven't been able to test yet is disarming the system after a fire/smoke alarm, and whether the smoke detectors accurately report as triggered in Homekit, and then not triggered after disarming the alarm.

You can find my code [here](https://github.com/dstapleton92/homebridge-envisalink). Make sure you read the note for developers I added to the bottom of the README. Mainly, you'll need to run `npm install` and then `npm run build` because the code is written in ES6 and will need to be transpiled to run in Node.

**Comment by dbeard** [comment]
Thanks - I have this running on my install currently. I was having issues with the original plugin. This appears to be working properly (for the most part). Planning on doing more testing, but some initial observations:

- You need to make sure you do a `npm link` to homebridge in the node module - this wasn't clear to me at first
- Alarm state seems to hang at first after arming or disarming. Swiping between rooms and closing the app seems to resolve it. Not sure if this is a plugin issue or homekit issue in general

**Comment by dstapleton92** [comment]
Thanks for the heads up. I'll check it out. The plugin "just works" for me due to the location of my global node_modules folder, but I definitely see now that most standard configs would require an `npm link`, which is not something I want to make people have to do. I'll figure out another way.

**Comment by dbeard** [comment]
Should I be getting a homekit alert when the alarm is triggered? I seem to get them when I arm/disarm, but not when the alarm is actually triggered

**Comment by dustindclark** [comment]
I believe the previous issues have been resolved.  Feel free to open a PR if there are additional shortcomings.
