### ISSUE TITLE
Homebridge ETIMEDOUT error

### ISSUE THREAD

**Issue by andyjohnclark** [dustindclark/homebridge-envisalink#39]
I am getting this error whenever I start homebridge on my raspberry pi.  I have an envisalink3.

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect **ETIMEDOUT** 192.168.0.10:4025
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)

Homebridge runs for about 2 minutes before I get this error and then homebridge dies.  During this 2 minute window where homebridge seems to be running, the Homekit app on my iphone appears to be able to read the status of the zones and alarm status.  Also, when I toggle alarm status changes on my iPhone, I can see the 'sendcommand' being issued in the homebridge console - but I never get the 'command ### acknowledged'.   No matter what I do or try, after 2 minutes, I get the ETIMEDOUT eror and homekit dies.   When Homebridge shuts down from this error, then Homekit on my iPhone shows "No Response" for all sensors and the alarm system.

I installed nodealarmproxy and created my nap.js.  Prior to starting homekit, I load the node (node nap.js).  I can see it issuing the 'sendcommand' for login and getting current status.  The status info is returned and zone status changes are continuously displayed whenever a zone is triggered or there is a change in alarm system status.

This is a new system setup and I am new to this whole process of using the homebridge-envisalink plugin with a raspberry pi.  Can anyone please help me figure out why envisalink3 is not acknowledging commands from homebridge and then timing out?

**Here is my nap.js for nodealarmproxy:**
var nap = require('./nodealarmproxy.js');

var alarm = nap.initConfig({ password:'user',
        serverpassword:'user',
        actualhost:'192.168.1.10',
        actualport:'4025',
        serverhost:'0.0.0.0',
        serverport:'4025',
        zone:7,
        partition:1,
        proxyenable:true,
        atomicEvents:true
});

**Here is my config.json for homebridge:**
{
	"bridge": {
		"name": "Homebridge-01",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"platforms": [{
		"platform": "Envisalink",
		"host": "192.168.0.10",
		"deviceType": "DSC",
		"password": "user",
		"pin": "####",     (hidden for security)
		"suppressZoneAccessories": false,
		"suppressClockReset": false,
		"partitions": [{
			"name": "Alarm"
		}],
		"zones": [{
				"name": "Kitchen Door to Garage",
				"type": "door",
				"partition": 1,
				"zoneNumber": 1
			},
			{
				"name": "Upper Deck Door",
				"type": "door",
				"partition": 1,
				"zoneNumber": 2
			},
			{
				"name": "Front Door",
				"type": "door",
				"partition": 1,
				"zoneNumber": 3
			},
			{
				"name": "Basement Motion",
				"type": "motion",
				"partition": 1,
				"zoneNumber": 5
			},
			{
				"name": "Office Motion",
				"type": "motion",
				"partition": 1,
				"zoneNumber": 6
			},
			{
				"name": "Living Room Motion",
				"type": "motion",
				"partition": 1,
				"zoneNumber": 7
			}
		],
		"userPrograms": [{
			"name": "Basement Smoke",
			"type": "smoke",
			"partition": 1
		}]
	}]
}

Thanks!

Andy

**Comment by rvs007** [comment]
Is there a comprehensive installation tutorial available online somewhere that gives me a step-by-step guide on how to integrate the Envisalink 3/4 into Homebridge?  (like what to install using npm, then editing any files with the relevant information)?  For reference, I just added the Envisalink 4 module to my DSC alarm system, and I'm already running Alarm Server on my Rasbpi3. I just want to integrate the Envisalink into my Homebridge setup for iOS.  Thanks a lot!

**Comment by andyjohnclark** [comment]
Here are the steps I went through to set up mine.   Hope it helps.


1.	**Update the raspberry pi**
	sudo apt-get update
	sudo apt-get upgrade   (“Y” to continue)

2.	**Install nodejs**
	curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
	sudo apt-get install -y nodejs

3.	**Verify nodejs installation was successful**
	node -v

4.	**Install homebridge:**
	sudo npm install -g --unsafe-perm homebridge

5.	**Install nodealarmproxy**
	This is for the Envisalink TPI (Third Party Interface)
	sudo npm install nodealarmproxy

6.	**create nap.js**
	sudo nano node_modules/nodealarmproxy/nap.js	  (actualhost is IP of Envisalink module)

Save the following into the nap.js file:
var nap = require('./nodealarmproxy.js');

var alarm = nap.initConfig({ password:'user',
        serverpassword:'user',
        actualhost:'192.168.1.10',
        actualport:'4025',
        serverhost:'0.0.0.0',
        serverport:'4025',
        zone:7,
        partition:1,
        proxyenable:true,
        atomicEvents:true
});

7.	**Edit homebridge config.json file**:

	sudo nano ~/.homebridge/config.json
	_To format and validate config.json code:  https://jsonformatter.curiousconcept.com/
	IMPORTANT : host is the IP address of the raspberry pi._

Save the following into the confit.json file (update host, password, pin and zone names to your system) :

_{  
   "bridge":{  
      "name":"Homebridge-01",
      "username":"CC:22:3D:E3:CE:30",
      "port":51826,
      "pin":"031-45-154"
   },
   "platforms":[  
      {  
         "platform":"Envisalink",
         "host":"192.168.1.20",
         "deviceType":"DSC",
         "password":"user",
         "pin":"9999",
         "suppressZoneAccessories":false,
         "suppressClockReset":false,
         "partitions":[  
            {  
               "name":"Alarm"
            }
         ],
         "zones":[  
            {  
               "name":"Kitchen Door to Garage",
               "type":"door",
               "partition":1,
               "zoneNumber":1
            },
            {  
               "name":"Upper Deck Door",
               "type":"door",
               "partition":1,
               "zoneNumber":2
            },
            {  
               "name":"Front Door",
               "type":"door",
               "partition":1,
               "zoneNumber":3
            },
            {  
               "name":"Basement Motion",
               "type":"motion",
               "partition":1,
               "zoneNumber":5
            },
            {  
               "name":"Upper Level Motion",
               "type":"motion",
               "partition":1,
               "zoneNumber":6
            },
            {  
               "name":"Living Room Motion",
               "type":"motion",
               "partition":1,
               "zoneNumber":7
            }
         ]
      }
   ],
 }_


**On one PuTTY terminal, run node:**
	node node_modules/nodealarmproxy/nap.js

**On second PuTTY terminal, start homebridge:**
	Homebridge



Helpful Links:
	https://github.com/nfarina/homebridge/blob/master/README.md
	https://www.npmjs.com/package/homebridge-envisalink
	https://www.npmjs.com/package/nodealarmproxy
https://community.openhab.org/t/setup-a-dsc-evl-3-proxy-with-nodealarmproxy/37228
	https://github.com/dustindclark/homebridge-envisalink/blob/master/package.json
http://www.eyezon.com/AccessingEnvisalinkApplicationNoteEZ.pdf
https://jsonlint.com/
https://jsonformatter.curiousconcept.com/
https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html
http://forum.eyez-on.com/FORUM/viewtopic.php?t=301
http://forum.eyez-on.com/FORUM/download/file.php?id=223&sid=e611bf05bceaac3139c5c1d15347e969

**Comment by rvs007** [comment]
@andyjohnclark So do we not have to install the homebridge-envisalink plugin?

**Comment by rvs007** [comment]
@andyjohnclark Also, if I already have Alarmserver running on the Raspi3 (for SmartThings integration), do I still need to have NodeAlarmProxy running, or can I utilize Alarmserver for both SmartThings and HomeBridge integration?

**Comment by rvs007** [comment]
@andyjohnclark I've added everything as per the instructions (thanks so much for posting them!!!) and I'm also getting the same error as you.   ETIMEDOUT
Did you ever find the solution to this problem?

**Comment by rvs007** [comment]
@andyjohnclark As posted 3 days ago, I'm getting the exact same ETIMEDOUT error as you.  For my setup, I have Alarmserver running for SmartThings at the same time on the Raspi3.  Do you happen to have the same setup (have Alarmserver running)?  I'm trying to figure out a solution to the ETIMEDOUT error.  Did you resolve your issue?

**Comment by rvs007** [comment]
Silly me...  I had the server ip set wrong... 192.168.0.xxx instead of 192.168.1.xxx ... fixed it and now it can communicate... but ran into another problem [#42](https://github.com/dustindclark/homebridge-envisalink/issues/42)

**Comment by andyjohnclark** [comment]
> @andyjohnclark So do we not have to install the homebridge-envisalink plugin?

Hi @rvs007, I'm not sure what you mean by "homebridge-envisalink" plugin.  I just installed homebridge and added code to the config.json.    I have not messed around with SmartThings or AlarmServer, but would appreciate any instructions  you can post on that.

My ETIMEDOUT error was also due to me having the wrong IP.   I apologize for not going back in here and adding that comment.

Also, unfortunately, I get the same errors when I try to disarm via Homekit.  I still have to go into the EyzOn app to disarm.   It is nice being able to see the alarm status in Home, but not ideal for toggling my security system on and off.   I haven't messed with it since.    If you figure this out, please let me know.

Thanks for helping!

**Comment by rvs007** [comment]
I got everything sorted out and it seems like I have the SmartThings and Homebridge implementation both working.  For the SmartThings implementation (with Alarmserver) I followed the instructions on [this github page](https://github.com/LXXero/DSCAlarm).  

I realized the same problem with my config.json file where I had inadvertently put the wrong IP address, so I got that corrected and the ETIMEDOUT error went away.

I hope someone will see my post #42 and could help us out.

**Comment by dustindclark** [comment]
Keep in mind that Envisalink integration is via socket...so only one connection is allowed.  NodeAlarmProxy wraps this socket and allows multiple clients to consume its api.  I don’t know what SmartThings’ implementation is, but unless it uses NodeAlarmProxy on Homebridge (which I highly doubt), I don’t see how this is working for you.  Unless maybe you have a newer version of Envisalink than I do, and it has better apis.

Dustin

**Comment by dustindclark** [comment]
The crash on misconfigured IP/port/password is fixed in 0.4.0-beta.3. Please re-open if you're still having issues on that version.
