### ISSUE TITLE
Starter info

### ISSUE THREAD

**Issue by iRayanKhan** [dustindclark/homebridge-envisalink#40]
Hello everyone,
I am planning on getting an Envisalink 3 module i'm assuming that the gen 3 works. My main issue is, how will I find the zones for my alarm since the house builders had programmed it. Also i'd kindly appreciate it if someone had a video showing this working in HomeKit. I counted my window sensors, doors, smoke alarms, etc. In total that's 48 accessories so i'd just like to see what it's like and how installation is. 

     Thanks,

**Comment by iRayanKhan** [comment]
Closed: This project seems inactive and I will seek a native homekit Honeywell alarm.

**Comment by peros550** [comment]
I’m using this plugin. The same zones you have in your physical setup will have to match with the zones in the plugin. You may opt for a simpler configuration and don’t include the zones. That’s just gives the alarm system with its basic capabilities (arm / disarm / alarm triggered). If you really can’t find out the zones, then I think you need to monitor the local keyboard for activity and at the same time open/close Windows. That could be a time lengthy process, you will need the help of another person but I can’t think of any other way to get information of your zones. Also please keep in mind that two or more sensors may be related to single zone, so the actual number of zones could be less than the number of accessories. Good luck
