### ISSUE TITLE
Siren Availability in Homekit

### ISSUE THREAD

**Issue by techoin** [dustindclark/homebridge-envisalink#45]
I am using this plug in to access my DSC security system in Homekit. It exposes all contact sensors/zones to Homekit. I was wondering if anyone has figured out way to expose Siren connected to security panel?

**Comment by dustindclark** [comment]
Closing in favor of https://github.com/dustindclark/homebridge-envisalink/issues/80 since this is the only exposed mechanism for triggering the siren.
