### ISSUE TITLE
Arming one partition sets other to disarmed

### ISSUE THREAD

**Issue by DeepPurple77** [dustindclark/homebridge-envisalink#47]
Hi @dustindclark,

I've been struggling to come up with a fix for an issue, unfortunately my Javascript / coding skills are just not good enough - I've tried and wracked my brain to try come up with a solution but to no avail.

The issue as the subject suggests is with 2 partition systems. If partition 1 is armed and I then arm partition 2 either via Home or on Keypad/Remote, Home will show partition 2 as arming and then armed. If I close Home or force a refresh, partition 2 will show armed but partition 1 will show off (unarmed). The same happens when first arming partition 2 and then 1, partition 2 will show off while partition 2 shows armed.

I believe that the issue is an update is sent to the "non-focused" partition to clear the status but after hours of trying, I cannot find a solution to only update the current partition and not both. I think the issue may be in the function "EnvisalinkPlatform.prototype.partitionUpdate" but I just cannot find a solution.

If you have any pointers or ideas, please let me know. I'm happy to test and provide a PR if it works, I just need to figure out a way to fix it.

Thanks!

**Comment by dustindclark** [comment]
Fixed and published in v0.2.14 thanks to @rafiqsarlie.
