### ISSUE TITLE
Wrong State after Reboot/Homebridge Reload 

### ISSUE THREAD

**Issue by peros550** [dustindclark/homebridge-envisalink#48]
Hi, many thanks for this wonderful plugin. It really helped me a lot. 
I have noticed the following behavior and I wanted to report it in case somebody could have a look.

If I reload homebridge, or reboot the device and the Alarm System is armed (Away), the plugin reports a wrong state as Disarmed. 

Is this expected?

**Comment by dustindclark** [comment]
Fixed, verified, and published in v0.2.14 thanks to @rafiqsarlie.
