### ISSUE TITLE
Stay mode changes to Away

### ISSUE THREAD

**Issue by djp714** [dustindclark/homebridge-envisalink#50]
I noticed when arming in "stay" mode, HomeKit initially shows "stay" but subsequently changes to "away". I checked the DSC panel and the alarm is still in "stay" mode. Is there any way to correct the Homekit alarm status? Thank you.

**Comment by dustindclark** [comment]
Confirmed bug with mapping Night > Away.  Stay and Away statuses are mapped properly.

**Comment by dustindclark** [comment]
Tested and confirmed that this is resolved in [PR-60](https://github.com/dustindclark/homebridge-envisalink/pull/60).  Please re-open with steps to recreate if you see further issues.
