### ISSUE TITLE
Shutting down service due to connection reset

### ISSUE THREAD

**Issue by gyulaf** [dustindclark/homebridge-envisalink#51]
homebridge-envisalink plug in 0.2.4 running on hoobs pi. Hoobs version 3.1.14 Homebridge version 4.50.
After working well for couple of hours the status of accessories are not updating.
When I want to change something, like changing alarm level, then Homebridge service is shutting down:

[Homebridge] sendcommand 0311C5
[Homebridge] [12/30/2019, 11:19:57] Error: read ECONNRESET
[Homebridge] at TCP.onStreamRead (internal/stream_base_commons.js:201:27)
[Homebridge] [12/30/2019, 11:19:57] Got SIGTERM, shutting down service...

If I restart the service everything is working fine for another couple of hours and then I will have the same problem again.

Let me know if you need more info.
Thank you

**Comment by jclark16** [comment]
I'm seeing the same behaviour since updating to version 0.2.13 of this plugin, and 1.1.6 of Homebridge.  Unfortunately I didn't make a note of the previous versions, but it has been a while since I last updated.

Same symptom as described - if I restart Homebridge then it works nicely for a while and then reports ECONNRESET when trying to set state on the alarm which results in a SIGTERM and Homebridge restarting itself automatically, but also results in the alarm being inaccessible if I'm out of the house.

**Comment by jclark16** [comment]
@dustindclark I found that the disconnection is happening as part of the proxy... I tried setting the proxyenable to false and haven't seen this issue since.  Looking at the proxy logic, I cannot see what benefit it is giving this code.  Is it necessary, or is it safe to disable it?

**Comment by dustindclark** [comment]
The proxy enables integration with other platforms.  Sockets only allow a single connection.  If you're only using homebridge with your envisalink, then you should definitely disable proxy.

Dustin

**Comment by jclark16** [comment]
I just saw another issue where you commented on the Smartthings.  That makes sense.  I guess we could make the proxy option configurable, but that seems like a kludge as this should work fine.  I think I'll throw some extra diag into nodealarmproxy and try to track down the source of the issue.

**Comment by readylmay** [comment]
I have disabled the proxy and I am am getting this error as well. I also need to reboot my EnvisaLink 4 to allow connections to start up again.

Any thing else I can do beside setting Proxy to false?

**Comment by jclark16** [comment]
> I have disabled the proxy and I am am getting this error as well. I also need to reboot my EnvisaLink 4 to allow connections to start up again.
> 
> Any thing else I can do beside setting Proxy to false?

@readylmay are you getting this error after disabling the proxy?  I haven't needed to reboot my EnvisaLink (I'm on 3, but I don't think that would make much difference) - just restart Homebridge.

**Comment by readylmay** [comment]
No, I am not anymore. It required a few reboot cycles of the EnvisaLink and restarted home bridge, but rock solid ever since.

**Comment by kmberi** [comment]
Hi Guys, real noob here, how do I turn off proxyenable?

**Comment by jclark16** [comment]
> Hi Guys, real noob here, how do I turn off proxyenable?

I'm submitting a PR to make this setting configurable.  If you are comfortable modifying code I can tell you where to modify the setting.

**Comment by kmberi** [comment]
> > Hi Guys, real noob here, how do I turn off proxyenable?
> 
> 
> 
> I'm submitting a PR to make this setting configurable.  If you are comfortable modifying code I can tell you where to modify the setting.

Happy to back up and try tinker with the code?

**Comment by kmberi** [comment]
> > Hi Guys, real noob here, how do I turn off proxyenable?
> 
> 
> 
> I'm submitting a PR to make this setting configurable.  If you are comfortable modifying code I can tell you where to modify the setting.

Happy to tinker?

**Comment by jclark16** [comment]
Sorry I missed this, @kmberi 

Someone can correct me if there is a better way to do this, but how I have been trying changes is to go into the node_modules/homebridge-envisalink folder on my system (/usr/lib/node_modules/homebridge-envisalink/) and modifying index.js, look for "proxyenable: true," on line 113 and set it to false.  Then restart home bridge to pick up the change.

**Comment by kmberi** [comment]
Worked like a charm! Many thanks.

**Comment by kmberi** [comment]
Actually it worked for a while, now getting this error when I try to arm the alarm

5/15/2021, 1:24:33 PM [Envisalink] Attempting to set alarm state on partition 1 Alarm to 2 NIGHT_ARM
5/15/2021, 1:24:33 PM [Envisalink] Arming alarm to Stay/Night.
5/15/2021, 1:24:33 PM Got SIGTERM, shutting down Bridge...

**Comment by jclark16** [comment]
Are you seeing it consistently?  I have seen that once or twice in the past few months, but not enough to try tackling it as it is a bit involved from my initial look around.

The nodealarmproxy library that this uses to do the actual communications with Envisalink does not have robust disconnection or error handling.  e.g. if it disconnects from the alarm for whatever reason, it doesn't try to re-establish a connection and instead throws an exception at the next command.  I've looked at it a bit and refactored some things, but that bit of code hasn't been updated in a while so I'm a bit worried about "fixing" something which may break certain behaviours that are being relied on.  As I also don't have an environment that would test the proxy capabilities I wouldn't be able to thoroughly verify that it was still functioning as expected.

**Comment by kmberi** [comment]
It's happening every time I try to arm the alarm.

**Comment by kmberi** [comment]
So my n00b mistake might help someone in future I had my EyezON.com password in the password section. Changed it to "user" and that was it. Feel pretty dumb but thrilled it's working now.

**Comment by dustindclark** [comment]
The crash from a bad password or IP address should be fixed in 0.4.0-beta.3. Please re-open if you're still having issues. Thanks.
