### ISSUE TITLE
Support for serial interface? (DSC IT-100)

### ISSUE THREAD

**Issue by TDT1969** [dustindclark/homebridge-envisalink#52]
I'm eager to get my DSC panel connected with HomeKit/Homebridge.  Years ago I setup the panel with my old Vera system using the DSC IT-100 keypad emulator (https://cms.dsc.com/download.php?t=1&id=16238), which I believe is quite similar to the Envisalink -- except with a serial interface.  I have an RS-232 adapter to USB connector on it and previously had it plugged into my Vera's USB port.

I now have a Raspberry Pi running Homebridge and I'm wondering if this project would support integration over USB.  I'd appreciate any advice you might have.  Link to the developer guide for the IT-100 is above.  Info on the Vera plug-in, which supports both Envisalink and IT-100 can be found here: http://code.mios.com/trac/mios_dscalarmpanel

**Comment by dustindclark** [comment]
This plugin is specifically for Envisalink panels.  Adding support for the IT-100 would be a complete rewrite and would really belong in a separate plugin.  Closing this out for now, but feel free to submit a PR.
