### ISSUE TITLE
How do I Get a Panel in Homekit?

### ISSUE THREAD

**Issue by sebastiangoldstein** [dustindclark/homebridge-envisalink#54]
I added my Envisilink to HOOBS.
All of my Alarm sensors show up in Homekit.
BUT, I Can't figure out how to Arm and Disarm the alarm.
Should a panel have appeared in Apple Home?
Do I have to add the Panel somewhere?

**Comment by dustindclark** [comment]
Your panel should also appear in the Home app under Default Room.  Let me know if this issue still persists.

**Comment by dustindclark** [comment]
Closing for now.  Please reopen if you're still having issues.
