### ISSUE TITLE
Wrong IP address supplied causes HB to restart

### ISSUE THREAD

**Issue by Pblondin123** [dustindclark/homebridge-envisalink#55]
Hi, when a wrong IP address is supplied, instead of simply reporting an error, currently the whole HB bombs (and auto restarts if we have this configured).   Would be a nice to add this user-dummy validation in the plugin.

**Comment by Rantaholic** [comment]
Came here looking for this. 

Same thing happening for me. If the IP address is incorrect or the envisalink module is not reachable for any reason when Homebridge starts then Homebridge quits and restarts constantly.

Maybe it could be made to just make a log entry of the fail and try to connect again every x minutes.

**Comment by Pblondin123** [comment]
i ended up making envisalink a static IP address, which is a band aid but i don't have the chance to swap IP addresses anymore.   Also i learned to disable the plugin before i power off the alarm system for maintenance.

**Comment by dustindclark** [comment]
Fixed in 0.4.0-beta.2.

**Comment by dustindclark** [comment]
1.0.0 published with fix.
