### ISSUE TITLE
Door & Windows Show Open When Closed

### ISSUE THREAD

**Issue by rob-allison-code** [dustindclark/homebridge-envisalink#6]
The door and window states are showing the opposite of what they are. Is there any way to flip this state?

**Comment by mahodder** [comment]
+1

As a quick workaround I changed this in: /usr/local/lib/node_modules/homebridge-envisalink/index.js

```
EnvisalinkAccessory.prototype.getContactPosition = function (callback) {
    if (this.status && this.status.send == "open") {
        callback(null, 0);
    } else {
        callback(null, 100);
    }
}
```

to:

```
EnvisalinkAccessory.prototype.getContactPosition = function (callback) {
    if (this.status && this.status.send == "open") {
        callback(null, 100);
    } else {
        callback(null, 0);
    }
}
```

and restarted homebridge.

**Comment by IMNotMax** [comment]
it works !
Thanks

But do you plan an official update ?

**Comment by rob-allison-code** [comment]
Thank you for the fix. It works very well. I can now do status updates on these and include them in alerts. I appreciate you fixing this issue so quickly.
