### ISSUE TITLE
add code request when disarming

### ISSUE THREAD

**Issue by jonsem2** [dustindclark/homebridge-envisalink#61]
Is there anyway to disarm system only when passwords entered?  I'd like to have an IPad at the intry point instead of my DSC screen, only concern is that disarming the system does not require a password.  May not be possible but thought i'd ask.

**Comment by dustindclark** [comment]
I don’t think HomeKit supports this, even for approved alarm panels.  You could leave the iPad locked though I suppose.  HomeKit will prevent disarming (even with Siri) unless the iPad is unlocked.

**Comment by jonsem2** [comment]
Agree homekit is where the restriction on this would be as I suspected, thank you for the quick response and amazing plugin!  I will probably setup my EyesOn app on IPAD since my ipad stays on for camera footages.

**Comment by dustindclark** [comment]
Closing since this is a HomeKit limitation.
