### ISSUE TITLE
Logging enhancements

### ISSUE THREAD

**Issue by jclark16** [dustindclark/homebridge-envisalink#63]
I find the logging from this module to be very busy.  Maybe it's because we have a couple of kids running around and a couple of motion sensors, but the amount of motion sensor notifications we get when the system is disarmed doesn't seem necessary.

If I were to submit a PR with some logging adjustments would anyone be offended?  Or should I make the logging level configurable through settings?

**Comment by dustindclark** [comment]
Sounds like 2 different things.  Is this a logging problem or a push notification problem?  The latter may not be a code problem with the plugin.

Either way,  PRs are never offensive.  Contributions are always appreciated.

Dustin

**Comment by jclark16** [comment]
Former, just diagnostic logging.  Between this and the Insteon module it was frustrating to filter through the noise to find issues.  I'll give it a go.

**Comment by jclark16** [comment]
I'm going to close this for now - it looks like there were a number of changes since I last updated that have improved things here already.
