### ISSUE TITLE
Add Home Armed

### ISSUE THREAD

**Issue by raphaeldavid** [dustindclark/homebridge-envisalink#66]
Would it be possible to add a state when the alarm is Home armed, in order to be able to make automations?

Thank,

**Comment by dustindclark** [comment]
This is already supported. Home and Night behave the same since DSC only supports one "Home" mode. I have automations already that are triggered based on alarm state. Re-open with the specific issue you're seeing if it's not working for you.

**Comment by raphaeldavid** [comment]
I can arm in Home... this is not the problem.

The problem is when I want to automate on activating Night.
In WHEN, I only have the choice of
- Alarm
- Disabled
- Enabled

Example
When I leave the house, the alarm is activated and the temperature adjusts to 16 ° C.
When I go to bed I would like to adjust the temperature to 22 ° C

Thank,

**Comment by dustindclark** [comment]
The automation limitation is a HomeKit limitation. It can't be added to the plugin until Apple supports it. See similar ticket here for a different alarm type: https://github.com/bryan-bartow/homebridge-alarm.com/issues/39

If/when apple supports this, the plugin should support it without requiring any changes.
