### ISSUE TITLE
Zones with different PINs?

### ISSUE THREAD

**Issue by skcuslleb** [dustindclark/homebridge-envisalink#68]
Hi there,

Is it possible to configure a system with 2 zones, but each zone has a different PIN?

**Comment by dustindclark** [comment]
Not currently.  Is that something your panel supports?

Dustin

**Comment by skcuslleb** [comment]
Yes! I thought most panels supported that feature? Here’s my scenario: I have 2 zones, 1 for my main unit and 1 for the separate basement suite. Each has its own PIN. I have them setup in Homebridge, and I can arm both but can only disarm the main unit.

Edit: sorry, I keep saying “zone” when I really mean “partition”. I can see that may be confusing.

**Comment by dustindclark** [comment]
Sounds like this would be a good improvement then...some bad assumptions on the initial implementation.

Dustin

**Comment by skcuslleb** [comment]
Reading through the code it looks like it will be as simple as moving the PIN node in the schema down into the partition properties, then deleting line 56 in index.js, and changing line 470 from "this.pin" to "this.partition.pin". I can probably test it out later this week...

**Comment by skcuslleb** [comment]
@dustindclark  I created 2 pull requests (sorry, I suck at GitHub stuff). I've tested and everything works well on my panel. I realize thought that this would break things for most people as it moves the pin in the config, so I'm not sure if there's a gentler way to do that for everyone.

**Comment by dustindclark** [comment]
Fixed in 0.4.0-beta.3. Please verify and I'll update when this version is released.
