### ISSUE TITLE
No compatibility for 'Night' mode on DSC system

### ISSUE THREAD

**Issue by xhi-nico** [dustindclark/homebridge-envisalink#72]
Hi there,

Plugin has worked flawlessly so far, thank you for building & supporting this. 

One question I have is related to the different arm modes; Home/Away/Stay/Night. Night is not an arm mode that is supported by my DSC system. Is this a setting that Apple allows to program and hide if it's not supported?

**Comment by dustindclark** [comment]
Howdy,

Not to my knowledge, but "Night" mode is coded such that it works like "Stay".  In fact, if you arm in "Night", the system will report as "Stay" after the exit delay.

**Comment by dustindclark** [comment]
Here are the modes supported by DSC:

```
export enum PartitionMode {
    Away = 0,
    Stay = 1,
    AwayZeroEntry = 2,
    StayZeroEntry = 3,
}
```

We could probably persist/remember when a user arms as NIGHT mode vs. STAY, but there would effectively be no difference. HomeKit doesn't currently provide the ability to create triggers on these states (other than ARM/DISARM/TRIGGERED). If there's a use case for HOME that I'm missing even though the panel doesn't support it, please reopen and I'll revisit.

**Comment by jmjlai** [comment]
sorry to drudge up an old thread, but my system (Power 832 / 5010) does not have a "Night" mode, so it's confusing to see it there. can the presence of "Night" mode be dependent on compatibility?
