### ISSUE TITLE
ERROR[Envisalink Bridge 2725@Alarm@Alarm@Security System Target State

### ISSUE THREAD

**Issue by scaryfast8750** [dustindclark/homebridge-envisalink#74]
When I use HomeKit to set my alarm two things happen:

1.  ERROR[Envisalink Bridge 2725@Alarm@Alarm@Security System Target State] SET handler returned write response value, though the characteristic doesn't support write response
2. Envisalink BridgeEnvisalinkSet status on partition 1 Alarm to 656 Exit Delay in Progress 

First question is are these related, they are sequential on the "arm" even for Home/Night mode.
Second question:  Why does the alarm set right away in stay mode in the house, but the plugin waits a 120 seconds for an exit delay on stay mode before HomeKit updates?  Is there a way to have "stay mode" update faster?

Other than this, all things work and function perfectly.  Please advise.

**Comment by dustindclark** [comment]
Can you install the 0.4.0-beta.2 and retest? This version is a full rewrite of the plugin.

**Comment by scaryfast8750** [comment]
I tried to install it in hoobs with a new bridge and plugin but it thinks its v0.2.18 still even thought I selected 0.4.  Let me work on this and see if I can get it to work correctly…it might just be hoobs being weird with the same plugin installed at two different versions.

**Comment by dustindclark** [comment]
It's published as a beta version. Not sure how you do it in HOOBS, but in Homebridge, you click the wrench icon on the plugin and select "Install previous version".

**Comment by dustindclark** [comment]
1.0.0 has been published. Please re-open if the issue persists in 1.0.0.

**Comment by scaryfast8750** [comment]
Dustin,

Not sure why but I cant see 1.0?   Here is a screenshot…the latest version of .4b3.

**Comment by dustindclark** [comment]
Screenshot didn't come through, but I'm not sure what .4b3 would be. How did you install the plugin initially?

**Comment by scaryfast8750** [comment]
Here is what im running:

Version	4.1.15 Check for Updates
Node Version	14.18.1
Homebridge Version	1.3.5
CPU	5%
Memory	187.1 MB (124.1 MB)
Manufacturer	HOOBS.org
Model	HSLF-2
System Version	10
SKU	7-45114-12418-0
Hostname	hoobs

When you click on Plugin’s you can install the envisalink plugin.  If you click on versions, here Is what it see:
Tags:
0.2.16 - Latest
0.4.0-beta.3 - beta

Releases
0.4.0-beta.3 - Nov 22
0.4.0-beta.2 - Nov 22
0.3.1-beta.0 - Nov 20
And so on.

Version 1 does not show up as “latest” in the UI.

If you want to send me an email address I can send you some screenshots.  I am also just checked for updates and im on the max version of all plugins and components.

S
