### ISSUE TITLE
Not Responding

### ISSUE THREAD

**Issue by tivo65** [dustindclark/homebridge-envisalink#75]
I cannot get the Envisalink hoobs plugin to communicate to my TYPE: EVL4 DSC
Version: 182 alarm module.  it won't show if zones open or shut (always shows closed) and won't arm or disarm the alarm.  below is my config and logs.  suggestions? (note that zone 14 is not used)

{
    "platform": "Envisalink",
    "password": "1111111111",
    "pin": "1111",
    "host": "192.168.10.12",
    "deviceType": "DSC",
    "suppressClockReset": true,
    "partitions": [
        {
            "name": "WMC Home"
        }
    ],
    "zones": [
        {
            "name": "1-Dbl Garage and Mud Entry",
            "partition": 1,
            "zoneNumber": 1,
            "type": "door"
        },
        {
            "name": "2-Front Door and Down Patio Entry",
            "partition": 1,
            "zoneNumber": 2,
            "type": "door"
        },
        {
            "name": "3-Single Garage and Up Patio Entry",
            "partition": 1,
            "zoneNumber": 3,
            "type": "door"
        },
        {
            "name": "4-Up Family Rm Windows",
            "partition": 1,
            "zoneNumber": 4,
            "type": "window"
        },
        {
            "name": "5-Up Laundry Win",
            "partition": 1,
            "zoneNumber": 5,
            "type": "window"
        },
        {
            "name": "6-Shed Entry",
            "partition": 1,
            "zoneNumber": 6,
            "type": "door"
        },
        {
            "name": "7-Dn Kitchen Win",
            "partition": 1,
            "zoneNumber": 7,
            "type": "window"
        },
        {
            "name": "8-Dn Fam Rm Win",
            "partition": 1,
            "zoneNumber": 8,
            "type": "window"
        },
        {
            "name": "9-Dn Hall Win",
            "partition": 1,
            "zoneNumber": 9,
            "type": "window"
        },
        {
            "name": "10-Dn West Bed Win",
            "partition": 1,
            "zoneNumber": 10,
            "type": "window"
        },
        {
            "name": "11-Dn Mid Bed Win",
            "partition": 1,
            "zoneNumber": 11,
            "type": "window"
        },
        {
            "name": "12-Dn East Bed Win",
            "partition": 1,
            "zoneNumber": 12,
            "type": "window"
        },
        {
            "name": "13-Green Rm Win",
            "partition": 1,
            "zoneNumber": 13,
            "type": "window"
        },
        {
            "name": "15-Up Motion Sensor",
            "partition": 1,
            "zoneNumber": 15,
            "type": "motion"
        },
        {
            "name": "16-Down Motion Sensor",
            "partition": 1,
            "zoneNumber": 16,
            "type": "motion"
        }
    ],
    "suppressZoneAccessories": false
}

8/31/2021, 8:48:02 PMenvisalink stopping
8/31/2021, 8:48:07 PMEnvisalink starting
8/31/2021, 8:48:10 PMEnvisalinkLoaded plugin 'homebridge-envisalink'
8/31/2021, 8:48:10 PMEnvisalinkLoading 1 platforms...
8/31/2021, 8:48:10 PMEnvisalinkEnvisalinkConfiguring Envisalink platform,  Host: 192.168.10.12, port: undefined, type: DSC
8/31/2021, 8:48:10 PMEnvisalinkEnvisalinkGenerated UUID 36f431e8-a869-4e88-b1aa-c18193e6f801 for accessory ID envisalink.1
8/31/2021, 8:48:10 PMEnvisalinkEnvisalinkGenerated UUID 769cc457-047f-4c76-ab44-8fcd67570fcf for accessory ID envisalink.1.1
8/31/2021, 8:48:10 PMEnvisalinkEnvisalinkGenerated UUID f8bb280b-c337-4136-a62a-12a2f83a81d8 for accessory ID envisalink.1.2
8/31/2021, 8:48:10 PMEnvisalinkEnvisalinkGenerated UUID 8ce38bbc-fa2b-4e94-87b3-41f79280d7c6 for accessory ID envisalink.1.3
8/31/2021, 8:48:10 PMEnvisalinkEnvisalinkGenerated UUID 1b5f4151-0309-4f1f-bf81-b9ca566253a9 for accessory ID envisalink.1.4
8/31/2021, 8:48:10 PMEnvisalinkEnvisalinkGenerated UUID 7fc5db4e-7d90-4438-b09d-b94527f38d40 for accessory ID envisalink.1.5
8/31/2021, 8:48:10 PMEnvisalinkEnvisalinkGenerated UUID e9e049f8-d4ae-403f-b127-89ab5c67b8ef for accessory ID envisalink.1.6
8/31/2021, 8:48:10 PMEnvisalinkEnvisalinkGenerated UUID 253b190a-02ca-4510-ae7a-dafeb3a82aeb for accessory ID envisalink.1.7
8/31/2021, 8:48:10 PMEnvisalinkEnvisalinkGenerated UUID e0b951f7-eb67-43e4-a55c-222c18b0bcf1 for accessory ID envisalink.1.8
8/31/2021, 8:48:10 PMEnvisalinkEnvisalinkGenerated UUID 3a771336-4a29-4fc2-9b91-bbc0f172ae3e for accessory ID envisalink.1.9
8/31/2021, 8:48:10 PMEnvisalinkEnvisalinkGenerated UUID fc23e1d5-9c6e-47d2-a21e-b5f78e3f8f3d for accessory ID envisalink.1.10
8/31/2021, 8:48:10 PMEnvisalinkEnvisalinkGenerated UUID 4cb9ef68-cd3c-43cb-acd7-e93b800e993c for accessory ID envisalink.1.11
8/31/2021, 8:48:10 PMEnvisalinkEnvisalinkGenerated UUID a81b7292-17d9-4c56-8f1b-ff9526679aae for accessory ID envisalink.1.12
8/31/2021, 8:48:10 PMEnvisalinkEnvisalinkGenerated UUID 1f0bc0e8-1c06-47db-adac-29554cd6abff for accessory ID envisalink.1.13
8/31/2021, 8:48:10 PMEnvisalinkEnvisalinkGenerated UUID 64f1f8a7-62dc-40c6-9319-186953e3f38e for accessory ID envisalink.1.15
8/31/2021, 8:48:10 PMEnvisalinkEnvisalinkGenerated UUID b361efc7-8455-425c-a930-829d247e8e9e for accessory ID envisalink.1.16
8/31/2021, 8:48:10 PMEnvisalinkEnvisalinkStarting node alarm proxy...
8/31/2021, 8:48:10 PMEnvisalinkEnvisalinkZone Config: 16
8/31/2021, 8:48:10 PMEnvisalinkEnvisalinkUser Program Config: null
8/31/2021, 8:48:10 PMEnvisalinkEnvisalinkNode alarm proxy started.  Listening for connections at: 0.0.0.0:4026
8/31/2021, 8:48:10 PMEnvisalinkBridge is running on port 51836.
8/31/2021, 8:50:35 PMEnvisalinkEnvisalinkAttempting to set alarm state on partition 1 WMC Home to 2 NIGHT_ARM
8/31/2021, 8:50:35 PMEnvisalinkEnvisalinkArming alarm to Stay/Night.
8/31/2021, 8:50:44 PMEnvisalink starting
8/31/2021, 8:50:47 PMEnvisalinkLoaded plugin 'homebridge-envisalink'
8/31/2021, 8:50:47 PMEnvisalinkLoading 1 platforms...
8/31/2021, 8:50:47 PMEnvisalinkEnvisalinkConfiguring Envisalink platform,  Host: 192.168.10.12, port: undefined, type: DSC
8/31/2021, 8:50:47 PMEnvisalinkEnvisalinkGenerated UUID 36f431e8-a869-4e88-b1aa-c18193e6f801 for accessory ID envisalink.1
8/31/2021, 8:50:47 PMEnvisalinkEnvisalinkGenerated UUID 769cc457-047f-4c76-ab44-8fcd67570fcf for accessory ID envisalink.1.1
8/31/2021, 8:50:47 PMEnvisalinkEnvisalinkGenerated UUID f8bb280b-c337-4136-a62a-12a2f83a81d8 for accessory ID envisalink.1.2
8/31/2021, 8:50:47 PMEnvisalinkEnvisalinkGenerated UUID 8ce38bbc-fa2b-4e94-87b3-41f79280d7c6 for accessory ID envisalink.1.3
8/31/2021, 8:50:47 PMEnvisalinkEnvisalinkGenerated UUID 1b5f4151-0309-4f1f-bf81-b9ca566253a9 for accessory ID envisalink.1.4
8/31/2021, 8:50:47 PMEnvisalinkEnvisalinkGenerated UUID 7fc5db4e-7d90-4438-b09d-b94527f38d40 for accessory ID envisalink.1.5
8/31/2021, 8:50:47 PMEnvisalinkEnvisalinkGenerated UUID e9e049f8-d4ae-403f-b127-89ab5c67b8ef for accessory ID envisalink.1.6
8/31/2021, 8:50:47 PMEnvisalinkEnvisalinkGenerated UUID 253b190a-02ca-4510-ae7a-dafeb3a82aeb for accessory ID envisalink.1.7
8/31/2021, 8:50:47 PMEnvisalinkEnvisalinkGenerated UUID e0b951f7-eb67-43e4-a55c-222c18b0bcf1 for accessory ID envisalink.1.8
8/31/2021, 8:50:47 PMEnvisalinkEnvisalinkGenerated UUID 3a771336-4a29-4fc2-9b91-bbc0f172ae3e for accessory ID envisalink.1.9
8/31/2021, 8:50:47 PMEnvisalinkEnvisalinkGenerated UUID fc23e1d5-9c6e-47d2-a21e-b5f78e3f8f3d for accessory ID envisalink.1.10
8/31/2021, 8:50:47 PMEnvisalinkEnvisalinkGenerated UUID 4cb9ef68-cd3c-43cb-acd7-e93b800e993c for accessory ID envisalink.1.11
8/31/2021, 8:50:47 PMEnvisalinkEnvisalinkGenerated UUID a81b7292-17d9-4c56-8f1b-ff9526679aae for accessory ID envisalink.1.12
8/31/2021, 8:50:47 PMEnvisalinkEnvisalinkGenerated UUID 1f0bc0e8-1c06-47db-adac-29554cd6abff for accessory ID envisalink.1.13
8/31/2021, 8:50:47 PMEnvisalinkEnvisalinkGenerated UUID 64f1f8a7-62dc-40c6-9319-186953e3f38e for accessory ID envisalink.1.15
8/31/2021, 8:50:47 PMEnvisalinkEnvisalinkGenerated UUID b361efc7-8455-425c-a930-829d247e8e9e for accessory ID envisalink.1.16
8/31/2021, 8:50:47 PMEnvisalinkEnvisalinkStarting node alarm proxy...
8/31/2021, 8:50:47 PMEnvisalinkEnvisalinkZone Config: 16
8/31/2021, 8:50:47 PMEnvisalinkEnvisalinkUser Program Config: null
8/31/2021, 8:50:47 PMEnvisalinkEnvisalinkNode alarm proxy started.  Listening for connections at: 0.0.0.0:4026
8/31/2021, 8:50:47 PMEnvisalinkBridge is running on port 51836.

**Comment by dustindclark** [comment]
Can you please test this in the 0.4.0-beta.2 version? If it fails, repost logs with debug turned on. Debug logging with the NodeAlarmProxy service is enabled in this branch.

**Comment by dustindclark** [comment]
1.0.0 published. Please re-open if this is still a problem.
