### ISSUE TITLE
Zones won't appear after HOOBS 4.0 upgrade

### ISSUE THREAD

**Issue by TDT1969** [dustindclark/homebridge-envisalink#78]
It appears the plug-in didn't survive the upgrade.  Removed Bridge from Home app. In Hoobs: uninstalled, reinstalled (creating new Envisalink bridge), created and saved new config file.  Added new accessory (bridge) to Home app.  Appeared to add successfully via UI and Envisalink Bridge shown in Home Settings but no Zones appear.

Looking at Hoobs logs I see this for each time I attempted to do this...

9/24/2021, 1:58:32 PMenvisalinkbridge stopping
9/24/2021, 1:58:37 PMEnvisalink Bridge starting
9/24/2021, 1:58:44 PMEnvisalink Bridge WARNING No plugins installed.
9/24/2021, 1:58:44 PMEnvisalink BridgeLoading 1 platforms...
9/24/2021, 1:58:45 PMEnvisalink BridgeBridge is running on port 51826.

**Comment by TDT1969** [comment]
Looking to see if anyone else has run into this issue that says "no plugins installed" despite the plugin being installed?

**Comment by dustindclark** [comment]
Can you try again with the latest version of the plugin?

**Comment by TDT1969** [comment]
Solved it!  Thanks so much!!!
