### ISSUE TITLE
Fire Alarm and Glass Break

### ISSUE THREAD

**Issue by erfind** [dustindclark/homebridge-envisalink#8]
Greetings!

First off, THANK YOU SO MUCH for this project! I was wondering if you would consider creating a fire detector and glass break sensor type?  Thank you again for your work, and I hope that you continue to make it even better!

Ethan

**Comment by dustindclark** [comment]
Hi @erfinb, I don't have any of those devices to test with.  If you have the time, feel free to create a pull request with support for those devices.  Thanks!

**Comment by erfind** [comment]
Hey! I am not super familiar with how GitHub works. What does doing a pull do? 🙂 (And how do I do it lol)

**Comment by ToddGreenfield** [comment]
I am working on adding a Water/Leak Sensor (testing now) and will also try to add a Smoke Sensor, but I don't have the ability to test the Smoke Sensor (don't have one hooked to my DSC) so @erfinb if you can test that would be great once ready. I don't think we can add a Glass Break as there is no corresponding Homekit (supported by HAP-NodeJS) accessory type for that. I looked and didn't see anything close to something logical to use.

**Comment by erfind** [comment]
I would be happy to help out 🙂

**Comment by erfind** [comment]
So I have the update installed and have switched the Smoke Detectors over in the confit file. However for some reason my Smoke Detectors are not connecting to the DSC unit. 😕

**Comment by ToddGreenfield** [comment]
@erfinb What type of detectors are they? Silly question but did you add them to your DSC alarm panel config? What DSC board do you have? Mine is an 1864-

**Comment by erfind** [comment]
The are wireless and are supposed to be on 7 and 8 I'm not sure why they aren't there anymore. Do you have any idea how to reprogram them into the system? The model numbers from my panel and DSC board are PC1616 and GS3060 if we can figure out how to read them then I can test it.

**Comment by erfind** [comment]
Sorry I was sending this from my iPhone while walking. I had to have our security company come out and remove their codes which led to me having to enter the different Sensors back into the system as far as what they were coded as. They were coded as smoke detectors and everything has seemed fine until I went to test them and discovered they are no longer communicating with the board. What's interesting is that the rest of the wireless contact Sensors for the windows are working. So perhaps adding them back in would work. I just don't know how you program them in with the ESN to specific codes such as 7 and 8 which I believe are zones? I'm still learning about how programming DSC panels works. 🙂

**Comment by ToddGreenfield** [comment]
It is not that difficult. If you are able to handle installing/running homebridge and adding modules/etc, you should be able to handle programming an alarm. Don't be intimidated, check out www.alarmsystemstore.com/help.asp, there are tons of support guides. For your system, which is the essentially the same as mine, look at http://www.alarmsystemstore.com/Articles.asp?ID=273.  I bought my entire system from them and there is a lot of online help available. If you have an existing alarm company managing it for you, I am assuming you don't have the installer code... something they would keep from you. If you are paying them to monitor I would guess you may want to keep using them. If you decide you want to self-monitor (such as via the envisalink board), you could just do a master reset/default to the board. But, you would need to reprogram everything - again, not really that difficult. Take a look at the link above and related docs for the 1616 on the web site above.

**Comment by ToddGreenfield** [comment]
Also, let me know if the smoke add-on for the plugin is working like it should. I wasn't sure if i had the logic backwards or not. :)

**Comment by erfind** [comment]
It works!!! 🙂 thanks for the great website too!

**Comment by dustindclark** [comment]
Closing.  Smoke accessory has been added, glass break is not yet available upstream.
