### ISSUE TITLE
Smoke status doesn't work in 1.0.0

### ISSUE THREAD

**Issue by dustindclark** [dustindclark/homebridge-envisalink#84]
I don't have smoke alarms to test with, so I need some help implementing this in 1.0.0

**Comment by bolducd** [comment]
1.0.0 nothing was working for me so could not test this.
1.0.3 I can use my alarm in homebridge this morning and I can see smoke detector tiles
Everything is back to default in the first room of my house but my smoke detectors are there. I suppose they work but can't test this in the morning.

**Comment by dustindclark** [comment]
I know for sure that smoke doesn't work in 1.0.x because I haven't written the code for handling smoke after the rewrite. If you can help test, I can work on getting a beta version out for this in a day or 2.

**Comment by bolducd** [comment]
Ok no problem. Let me know when the beta is ready to test.

**Comment by dustindclark** [comment]
If you get a chance, can you change config on the plugin to `"enableVerboseLogging": true`, enable debug in Homebridge, then trigger your smoke sensor? You should see a log that starts with `Inside systemUpdate: XXX`. I need to know what's in the XXX.

The reason I ask is that I think the previous implementation could be better. I think NodeAlarmProxy is incorrectly [processing these events as system updates](https://github.com/NodeAlarmProxy/NodeAlarmProxy/blob/master/envisalink.js#L380), and the old version of the plugin was [stripping off zone/partition information](https://github.com/dustindclark/homebridge-envisalink/blob/before-typescript/index.js#L179), and the result is that smoke events are triggered on all smoke sensors in all partitions. I could be wrong...this may be a limitation with Envisalink (the [TPI doc](https://incedo.org/~sjoholmp/Fibaro_Homecenter/LUA/VDs/HC2_DSCengine/EnvisaLinkTPI-1-08.pdf) doesn't mention zone/partition context for smoke events), but I'd like to fix the logic if it's possible to do so.

**Comment by bolducd** [comment]
I did enable verbose for plugin and homebridge. I will test trigger the smoke zone later can't be done now for noise reason and let you know the result. 
Smoke event are normally associated with a zone/partition. I get an email from eyezon with the zone from the smoke detector triggered. But this depend on the kind of smoke detector you are using and it could be why NodeAlarmProxy doesn't do it by zone.

Wireless smoke detector use a zone like any other device.
2-wire smoke detector don't, they are connected to  pgm2 (no zone involved)
4-wire smoke detector, never used them but I think they are all connected to the same zone (all on the same zone/partition)

**Comment by dustindclark** [comment]
It may be a limitation of the third party interface for Envisalink, but we'll know once you're able to test. The 631/632 status codes should be suffixed with either a partition or zone. If not, we'll have to toggle smoke to true on all smoke zones.

Make sure to turn on `enableVerboseLogging` in the homebridge-envisalink's plugin config. That's a specific setting to turn on logging communication with envisaging.

Thanks for the help.

**Comment by bolducd** [comment]
![image](https://user-images.githubusercontent.com/73037674/144148921-b9db1359-95f5-4baf-a15b-457f867ed1c3.jpeg)

are you sure you did not code it?



Zone 024 is open
[11/30/2021, 7:10:16 PM] [Envisalink] Inside zoneUpdate: {
  "evtType": "zoneUpdate",
  "zone": 24,
  "code": "609",
  "status": "open",
  "zoneLabel": "Zone-24"
}
[11/30/2021, 7:10:16 PM] [Envisalink] Restoring existing zone accessory from cache: Feu RC
[11/30/2021, 7:10:16 PM] [Envisalink] Setting accessory details for zone: {
  "name": "Feu RC",
  "type": "smoke",
  "number": 24,
  "partition": 1,
  "status": {
    "shortCode": "609",
    "longCode": "609",
    "description": "Zone Open",
    "text": "open",
    "action": "updatezone",
    "verbSuffix": "is open"
  }
}
[11/30/2021, 7:10:16 PM] [Envisalink] Feu RC is a smoke sensor. Binding.
[11/30/2021, 7:10:16 PM] [Envisalink] Feu RC is open
Keypad LED State: C0 
Partition 1 is NOT Ready
[11/30/2021, 7:10:16 PM] [Envisalink] Inside partitionUpdate: {
  "evtType": "partitionUpdate",
  "partition": 1,
  "code": "651",
  "status": "notready"
}

**Comment by dustindclark** [comment]
hahaha. Maybe I did? The partition update (651 code) is unhandled, but I do detect when a zone is open/closed. If that zone is a smoke zone, then it [indeed sends smoke detected](https://github.com/dustindclark/homebridge-envisalink/blob/master/src/zoneAccessory.ts#L91).

In this case, I'm not sure why [this was necessary](https://github.com/dustindclark/homebridge-envisalink/blob/before-typescript/index.js#L179) in the old version of the plugin. Maybe @tech165 has context since it was his or her [PR](https://github.com/dustindclark/homebridge-envisalink/pull/5)?

**Comment by dustindclark** [comment]
Closing this out. @tech165 , feel free it reopen if you feel it's necessary.
