### ISSUE TITLE
Enhancement - Stateful switch for "Chime"

### ISSUE THREAD

**Issue by readylmay** [dustindclark/homebridge-envisalink#86]
Enabled a switch that toggle chime and off. One for each partition I suppose.

**Comment by dustindclark** [comment]
I added this in 1.0.0. Set `enableChimeSwitch` to true in your partition config and restart. Long press your partition in HomeKit to see the Chime switch.

Note that the only way to fetch status is to toggle chime on the system...so when Homebridge starts, Chime will be toggled twice (on then off, or off then on - depending on current state). I haven't seen any issues with this "hack", but something to be aware of in case you notice Chime turning on/off uncommanded. This could happen if the toggle fails on startup for whatever reason.

**Comment by ghost** [comment]
I have seriously tried to unsubscribe from this so many time and I keep getting bombarded with emails. PLEASE take me off the list
