### ISSUE TITLE
Last 3 zones are not showing up in 1.0.x

### ISSUE THREAD

**Issue by fifibest** [dustindclark/homebridge-envisalink#87]
Hi!

Since the latest update, my last 3 zones are not showing up. All the previous ones are there. This was working on the previous versions correctly:

                {
                    "name": "Window 2",
                    "partition": 1,
                    "zoneNumber": 12,
                    "type": "window"
                },
                {
                    "name": "Window 3",
                    "partition": 1,
                    "zoneNumber": 13,
                    "type": "window"
                },
                {
                    "name": "Window 4",
                    "partition": 1,
                    "zoneNumber": 14,
                    "type": "window"
                },

I have non-consecutive zones 1-4, 7, 9-14, the ones that are not showing up are 12-14.

I have one more "window" type zone, 11, that shows correctly. I tried switching the order in the config, or changing name, cleared homebridge cache, but it's always these 3 zones not showing (the last 3 zones).

No error message during startup.

**Comment by dustindclark** [comment]
Fixed in 1.0.3. Sorry for the breaking change.

**Comment by fifibest** [comment]
Thank you for quickly fixing it!
