### ISSUE TITLE
Question about Alarm Notification

### ISSUE THREAD

**Issue by peros550** [dustindclark/homebridge-envisalink#89]
Today, I had my parents entering into the house. The DSC alarm system was armed to away. It looks, they didn't enter the password too quickly or correct and the alarm sounded for a few seconds until they pressed the password correctly. 

My question: Meantime, I received an email from EyezON but I didn't receive a notification from Homekit (as I regularly do) about the Alarm. Is it this situation expected ? Is the alarm status passed to the plugin by i.e. poll?

**Comment by dustindclark** [comment]
The message should be pushed from the alarm to Homebridge, so no polling is required. Demo attached. Do you have notifications turned on for your alarm panel in HomeKit?

https://user-images.githubusercontent.com/3819936/145853496-4637f82e-e0c6-4178-8978-6dd2d18c9901.mp4

I suppose the socket connection could have died...I probably need to do some testing after the rewrite to see how resilient the connections are after an interruption/disconnect.

**Comment by peros550** [comment]
I do get notifications from my alarm. For example when arming/disarming. This new notification demonstrated in your message above , when the alarm is sound,  is something I started receiving in the last few versions, very cool. That’s what I expected to receive but I didn’t, and I thought it may has to do with disarming from the panel. 

One more idea to consider: would it be possible to have a notification when electricity is cut ?

use case: probably someone may think that when no electricity , the router or the Apple TV would have no power. However, if these devices run on UPS, and the alarm system usually has its own battery,  then it makes sense to get this information, especially if you are out of home.

**Comment by readylmay** [comment]
+1 for power trouble alert.

**Comment by dustindclark** [comment]
Do you have an example device/plugin that sends notifications like this? The "alarming" notification is something that is baked into HomeKit...the plugin doesn't send this out.

I could probably create a dummy contact sensor for system trouble in general, but you'd have to explicitly turn on notifications and the notification would not be marked "critical".

**Comment by peros550** [comment]
No, I haven't seen other plugins taking advantage of the time critical notifications. Probably Homekit gives high priority to an Alarm system on the notifications department. A second alarm system (virtual) would do the trick, but it's totally up to you. Many thanks for considering it. 

In the coming weekend, I will test myself the above case. I will have the Alarm sound and then quickly enter the password to check for any notification failures. At the same time, I will try to gather some logs.

**Comment by peros550** [comment]
Returning back to the original issue, today I had the chance to make the alarm sound and quickly disarm it. I couldn’t reproduce the issue. In fact, notification arrived almost instantly. I think we can close this issue unless anybody had a similar experience.

**Comment by dustindclark** [comment]
Sounds good. Thank you.
