### ISSUE TITLE
System Always Arming as Away

### ISSUE THREAD

**Issue by erfind** [dustindclark/homebridge-envisalink#9]
I recently did an update and now the alarm is always setting as Away, no matter how HomeKit tells it to arm itself, i.e. Home.

**Comment by erfind** [comment]
Is anyone else experiencing this? :)

**Comment by ToddGreenfield** [comment]
I am able to arm with "Home/Night" and it arms as Stay on the panel.

**Comment by erfind** [comment]
Darn, I wonder what's up with mine.
