### ISSUE TITLE
Connection Errors only emitted with verbose logging enabled

### ISSUE THREAD

**Issue by JDonovanH** [dustindclark/homebridge-envisalink#92]
I have the plugin installed on the latest version of Homebridge, and when it boots, the messages that display in the status window make me think it's working:
[11/01/2022, 22:29:46] [Envisalink] Initializing Envisalink platform...
[11/01/2022, 22:29:46] [Envisalink] Configuring Envisalink platform,  Host: 192.168.1.27 Port: 4025
[11/01/2022, 22:29:46] [Envisalink] Node alarm proxy started.  Listening for connections at: 0.0.0.0:4026
[11/01/2022, 22:29:46] [Envisalink] Panic buttons disabled. Will not install panic switches.

The only thing that looks strange to me is the "Listening for connections at 0.0.0.0"

However, no accessories appear for my alarm system. What am I missing? I have configured all the zones, including my unused ones. Here's a copy of the plugin json (with password and PIN removed):
{
    "host": "192.168.1.27",
    "password": "!",
    "pin": "",
    "port": 4025,
    "proxyPort": 4026,
    "enableVerboseLogging": false,
    "suppressZoneAccessories": false,
    "suppressClockReset": true,
    "policePanic": {
        "enabled": false,
        "name": "Police Panic"
    },
    "ambulancePanic": {
        "enabled": false,
        "name": "Ambulance Panic"
    },
    "firePanic": {
        "enabled": false,
        "name": "Fire Panic"
    },
    "partitions": [
        {
            "name": "Alarm",
            "enableChimeSwitch": true
        }
    ],
    "zones": [
        {
            "name": "Front Entry Motion",
            "partition": 1,
            "zoneNumber": 1,
            "type": "motion"
        },
        {
            "name": "Kitchen Motion",
            "partition": 1,
            "zoneNumber": 2,
            "type": "motion"
        },
        {
            "name": "Great Room Glass",
            "partition": 1,
            "zoneNumber": 3,
            "type": "window"
        },
        {
            "name": "Kitchen Glass",
            "partition": 1,
            "zoneNumber": 4,
            "type": "window"
        },
        {
            "name": "Front Door",
            "partition": 1,
            "zoneNumber": 5,
            "type": "door"
        },
        {
            "name": "Patio Door",
            "partition": 1,
            "zoneNumber": 6,
            "type": "door"
        },
        {
            "name": "Garage Service Door",
            "partition": 1,
            "zoneNumber": 7,
            "type": "door"
        },
        {
            "name": "Back Door",
            "partition": 1,
            "zoneNumber": 8,
            "type": "door"
        },
        {
            "name": "Den Window",
            "partition": 1,
            "zoneNumber": 9,
            "type": "window"
        },
        {
            "name": "Basement Glass",
            "partition": 1,
            "zoneNumber": 10,
            "type": "window"
        },
        {
            "name": "Family Room Window",
            "partition": 1,
            "zoneNumber": 11,
            "type": "window"
        },
        {
            "name": "Guest Bedroom Window",
            "partition": 1,
            "zoneNumber": 12,
            "type": "window"
        },
        {
            "name": "Unused 13",
            "partition": 1,
            "zoneNumber": 13
        },
        {
            "name": "Unused 14",
            "partition": 1,
            "zoneNumber": 14
        },
        {
            "name": "Unused 15",
            "partition": 1,
            "zoneNumber": 15
        },
        {
            "name": "Unused 16",
            "partition": 1,
            "zoneNumber": 16
        }
    ],
    "platform": "Envisalink"
}

**Comment by dustindclark** [comment]
0.0.0.0 is effectively localhost, so that's fine. Enable verbose logging in the plugin config, and then turn on Homebridge debug. If that doesn't help, post your plugin config.

Dustin

**Comment by JDonovanH** [comment]
Thanks so much for the quick response, Dustin. Once I enabled verbose logging, I found the problem right away because it said my password was wrong. It appears that the Envisalink truncates passwords longer than 10 characters and I had attempted to set it to one longer than that and is what I put in the plugin json. Once I truncated the password in the json, it worked great! Thanks again!

**Comment by dustindclark** [comment]
Good deal. Glad you got it working. I'm going to repurpose this issue to improve error logging without the need to turn on verbose logging.

**Comment by dustindclark** [comment]
Fixed in 1.1.1
