### ISSUE TITLE
"Second set chime failed" on startup

### ISSUE THREAD

**Issue by jmjlai** [dustindclark/homebridge-envisalink#94]
On start, I'm receiving the following message. I suspect it may be because of the hack used to toggle the chime twice.
The DSC menu 071 option 4 does not relate to the chime on all models. on my system (PC5010), it relates to "Interior Arm prompt"
On the PC5010, the chime is menu 070 option 5, or simply the user code '*4'.

`[homebridge-envisalink] Second set chime failed while fetching status Error: Command 0711*4 resulted in 010 error from alarm
    at /homebridge/node_modules/homebridge-envisalink/src/platform.ts:367:28
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-envisalink/node_modules/nodealarmproxy/nodealarmproxy.js:304:9)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
`

I suspect this is the snippet that causes the error, from platform.ts, which assumes the use of partition 1, which may or may not be how the TPI performs the same function.
`
// Wait 10 seconds for initial system startup (i.e. time sync).
const chimeCommand = `071${partition.number}*4`;
`

**Comment by dustindclark** [comment]
@jmjlai Try upgrading to 1.0.5 and specifying a chimeCommandOverride in your config.

**Comment by jmjlai** [comment]
@dustindclark my mistake, I was looking at the DSC option mask, not the Envisalink TPI.
The command "071${partition.number}*4" is correct (sorry), however the the TPI is throwing error "10" for a keybus TX buffer overrun.
I suspect since these commands are being issued in sequence there is a need for a slight delay between the first and second toggle.
From the TPI manual "In cases where a BUSY or BUFFER_OVERRUN code are encountered, the application should retry after a small delay period."

**Comment by dustindclark** [comment]
Added a delay in 1.0.9, but I can't recreate this error. Can you try again in 1.0.9 and let me know the results?

**Comment by jmjlai** [comment]
Hey @dustindclark both 1.0.9, 1.0.10, and 1.0.12 startup without error, Thanks!
I'm running a 33 year old panel, so I wouldn't be surprised if it gets overwhelmed easily.
I'd say you could revert the chime toggle command override.

**Comment by dustindclark** [comment]
Make sure to update to 1.1.0 when you get a chance. I broke "night" mode in the versions you've mentioned, and it has been fixed to work with a zero entry delay (see #99).
