### ISSUE TITLE
[Envisalink] actual disconnected

### ISSUE THREAD

**Issue by HerbM3** [dustindclark/homebridge-envisalink#95]
I just ditched Home Assistant and installed Homebridge (both running in Docker) specifically for your plug-in. Unfortunately, I keep getting this: 

[1/31/2022, 3:07:03 PM] [Envisalink] server bound
[1/31/2022, 3:07:03 PM] [Envisalink] actual connected
[1/31/2022, 3:07:13 PM] [Envisalink] actual disconnected

Any ideas what could be happening? Everything was fine in HA.

**Comment by dustindclark** [comment]
Enable verbose logging in the plugin config, then turn on Homebridge debug and restart. The connection failure reason will then be logged. The most likely reasons are:

- incorrect password configured (this password is different from your EyezOn account password and your alarm PIN).
- incorrect IP address.
- Envisalink socket already open from another device. In your case, you probably need to shut down HA or remove the plugin and restart (I'm not familiar with HA, so I'm not sure what this process looks like). The Envisalink will only support one connection at a time, but you can use my plugin to create a proxy as a workaround.

I [have an issue open already](https://github.com/dustindclark/homebridge-envisalink/issues/92) to improve connection error logging.

**Comment by HerbM3** [comment]
I deleted HA prior to posting here. I'm not sure I have debug turned on properly, because I'm not really seeing anything more than what verbose was showing.

I have triple checked my IP and reset my device password. I have rebooted it from the Eyezon site.

**Comment by dustindclark** [comment]
You'll have to turn on both verbose logging (via plugin config) and verbose logging (in Homebridge config, which can be enabled on the Homebridge web console). I'm planning to make this easier in a future version.

Dustin

**Comment by HerbM3** [comment]
I have turned on debug. I have deleted and reinstalled Homebridge in Docker on my NUC. Then I installed Hoobs on a RPi; same disconnect. I have rebooted the Envisalink. I removed power to it. I have changed the password. Nothing seems to work.

**Comment by dustindclark** [comment]
I really can't help unless you follow the steps I've mentioned and then provide the error logs generated. Did you enable verbose logging in the plugin config before restarting? See screenshot.

![Screen Shot 2022-02-01 at 12 55 54 AM](https://user-images.githubusercontent.com/3819936/151925118-3162bb07-0890-4b6b-b6ab-27f4ef8d45c8.png)

**Comment by HerbM3** [comment]
I think I'm to blame... I assumed this worked with the Honeywell Vista 20P. The specific Honeywell-Ademco plug works.

I'm including my log just in case
[homebridge.log.txt](https://github.com/dustindclark/homebridge-envisalink/files/7981078/homebridge.log.txt)

**Comment by dustindclark** [comment]
If you have an Envisalink hooked up to your panel, it should still work.

The attached log doesn't have verbose logging enabled in the plugin config, so it's not going to show the reason for the connection failure.

**Comment by dustindclark** [comment]
Closing this out. Let me know if there's anything further to investigate.
