### ISSUE TITLE
A Function Selected on Partition 1 is not Available

### ISSUE THREAD

**Issue by anupchavda1** [dustindclark/homebridge-envisalink#98]
Hi Dustin.

This was working a while back and then I  think a patch or 2 ago broke the reporting and the ability to arm/disarm the system.

I can see that the system sees the zones, and I can trigger and arm command, but I am getting:
A Function Selected on Partition 1 is not Available
further I am getting that Partition11 is armed ...not sure what partition 11 is:

my config: {
            "host": "192.168.1.xx",
            "password": "xxxx",
            "pin": "xxxx",
            "port": 4025,
            "proxyPort": 4026,
            "enableVerboseLogging": true,
            "suppressZoneAccessories": true,
            "suppressClockReset": false,
            "policePanic": {
                "enabled": false,
                "name": "Police Panic"
            },
            "ambulancePanic": {
                "enabled": false,
                "name": "Ambulance Panic"
            },
            "firePanic": {
                "enabled": false,
                "name": "Fire Panic"
            },
            "partitions": [
                {
                    "name": "Alarm",
                    "enableChimeSwitch": false,
                    "pin": "xxxx"
                }
            ],
            "zones": [
                {
                    "name": "Spare Bedroom",
                    "partition": 1,
                    "zoneNumber": 1,
                    "type": "motion"
                },
                {
                    "name": "Master Bedroom",
                    "partition": 1,
                    "zoneNumber": 2,
                    "type": "motion"
                },
                {
                    "name": "Landing",
                    "partition": 1,
                    "zoneNumber": 3,
                    "type": "motion"
                },
                {
                    "name": "Shaya Bedroom",
                    "partition": 1,
                    "zoneNumber": 4,
                    "type": "motion"
                },
                {
                    "name": "Computer Room",
                    "partition": 1,
                    "zoneNumber": 5,
                    "type": "motion"
                },
                {
                    "name": "Hall",
                    "partition": 1,
                    "zoneNumber": 6,
                    "type": "motion"
                },
                {
                    "name": "Living Room",
                    "partition": 1,
                    "zoneNumber": 7,
                    "type": "motion"
                },
                {
                    "name": "Cloakroom",
                    "partition": 1,
                    "zoneNumber": 8,
                    "type": "motion"
                },
                {
                    "name": "Dining Room",
                    "partition": 1,
                    "zoneNumber": 9,
                    "type": "motion"
                },
                {
                    "name": "Kitchen",
                    "partition": 1,
                    "zoneNumber": 10,
                    "type": "motion"
                },
                {
                    "name": "Bell Tamper",
                    "partition": 1,
                    "zoneNumber": 11,
                    "type": "door"
                },
                {
                    "name": "Bathroom",
                    "partition": 1,
                    "zoneNumber": 12,
                    "type": "motion"
                },
                {
                    "name": "DNU Zone1",
                    "partition": 1,
                    "zoneNumber": 13,
                    "type": "motion"
                },
                {
                    "name": "DNU Zone2",
                    "partition": 1,
                    "zoneNumber": 14,
                    "type": "motion"
                },
                {
                    "name": "DNU Zone3",
                    "partition": 1,
                    "zoneNumber": 15,
                    "type": "motion"
                },
                {
                    "name": "DNU Zone4",
                    "partition": 1,
                    "zoneNumber": 16,
                    "type": "motion"
                },
                {
                    "name": "DNU Zone5",
                    "partition": 1,
                    "zoneNumber": 17,
                    "type": "motion"
                },
                {
                    "name": "DNU Zone6",
                    "partition": 1,
                    "zoneNumber": 18,
                    "type": "motion"
                },
                {
                    "name": "DNU Zone7",
                    "partition": 1,
                    "zoneNumber": 19,
                    "type": "motion"
                },
                {
                    "name": "DNU Zone8",
                    "partition": 1,
                    "zoneNumber": 20,
                    "type": "motion"
                },
                {
                    "name": "DNU Zone9",
                    "partition": 1,
                    "zoneNumber": 21,
                    "type": "motion"
                },
                {
                    "name": "DNU Zone10",
                    "partition": 1,
                    "zoneNumber": 22,
                    "type": "motion"
                },
                {
                    "name": "DNU Zone11",
                    "partition": 1,
                    "zoneNumber": 23,
                    "type": "motion"
                },
                {
                    "name": "DNU Zone12",
                    "partition": 1,
                    "zoneNumber": 24,
                    "type": "motion"
                },
                {
                    "name": "Front Door",
                    "partition": 1,
                    "zoneNumber": 25,
                    "type": "door"
                },
                {
                    "name": "Porch",
                    "partition": 1,
                    "zoneNumber": 26,
                    "type": "door"
                },
                {
                    "name": "Patio Door",
                    "partition": 1,
                    "zoneNumber": 27,
                    "type": "door"
                },
                {
                    "name": "Kitchen Door",
                    "partition": 1,
                    "zoneNumber": 28,
                    "type": "door"
                },
                {
                    "name": "Kitchen Window",
                    "partition": 1,
                    "zoneNumber": 29,
                    "type": "window"
                },
                {
                    "name": "Shed",
                    "partition": 1,
                    "zoneNumber": 30,
                    "type": "door"
                },
                {
                    "name": "Living Room Window Left",
                    "partition": 1,
                    "zoneNumber": 31,
                    "type": "window"
                },
                {
                    "name": "Living Room Window Right",
                    "partition": 1,
                    "zoneNumber": 32,
                    "type": "window"
                }
            ],
            "platform": "Envisalink"
        },

The log: 
[2/21/2022, 10:49:24 PM] [Envisalink] sendcommand 0311C5
[2/21/2022, 10:49:24 PM] [Envisalink] Command 031 Acknowledged
[2/21/2022, 10:49:25 PM] [Envisalink] Keypad LED State: 8B 
[2/21/2022, 10:49:25 PM] [Envisalink] Exit Delay of Partition 1 in Progress
[2/21/2022, 10:49:55 PM] [Envisalink] Keypad LED State: 8A 
[2/21/2022, 10:49:56 PM] [Envisalink] Partition 1 has been armed by Quick Arm, Auto Arm, Keyswitch, DLS or Wireless Key
[2/21/2022, 10:49:56 PM] [Envisalink] Partition 11 is Armed

**Comment by readylmay** [comment]
This is simalar to #90

**Comment by dustindclark** [comment]
Please try this again on v1.1.0, and re-open if necessary. #90 is fixed in 1.1.0
